
package com.sforce.soap.enterprise;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-hudson-2079-RC1
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "InvalidIdFault", targetNamespace = "urn:fault.enterprise.soap.sforce.com")
public class InvalidIdFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.sforce.soap.enterprise.fault.InvalidIdFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InvalidIdFault(String message, com.sforce.soap.enterprise.fault.InvalidIdFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public InvalidIdFault(String message, com.sforce.soap.enterprise.fault.InvalidIdFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.sforce.soap.enterprise.fault.InvalidIdFault
     */
    public com.sforce.soap.enterprise.fault.InvalidIdFault getFaultInfo() {
        return faultInfo;
    }

}
