/**
 * JiraSoapService.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.easyinsight.datafeeds.jira.jiraweb;

public interface JiraSoapService extends java.rmi.Remote {
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteComment getComment(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteGroup createGroup(java.lang.String in0, java.lang.String in1, com.easyinsight.datafeeds.jira.jiraweb.RemoteUser in2) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteServerInfo getServerInfo(java.lang.String in0) throws java.rmi.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteGroup getGroup(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public java.lang.String login(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteUser getUser(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteUser createUser(java.lang.String in0, java.lang.String in1, java.lang.String in2, java.lang.String in3, java.lang.String in4) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteIssue getIssue(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteIssue createIssue(java.lang.String in0, com.easyinsight.datafeeds.jira.jiraweb.RemoteIssue in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteNamedObject[] getAvailableActions(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteIssue updateIssue(java.lang.String in0, java.lang.String in1, com.easyinsight.datafeeds.jira.jiraweb.RemoteFieldValue[] in2) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteConfiguration getConfiguration(java.lang.String in0) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteComponent[] getComponents(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteSecurityLevel getSecurityLevel(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteProject updateProject(java.lang.String in0, com.easyinsight.datafeeds.jira.jiraweb.RemoteProject in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteProject getProjectByKey(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemotePriority[] getPriorities(java.lang.String in0) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteResolution[] getResolutions(java.lang.String in0) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteIssueType[] getIssueTypes(java.lang.String in0) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteStatus[] getStatuses(java.lang.String in0) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteIssueType[] getSubTaskIssueTypes(java.lang.String in0) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteProjectRole[] getProjectRoles(java.lang.String in0) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteProjectRole getProjectRole(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteProjectRoleActors getProjectRoleActors(java.lang.String in0, com.easyinsight.datafeeds.jira.jiraweb.RemoteProjectRole in1, com.easyinsight.datafeeds.jira.jiraweb.RemoteProject in2) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteRoleActors getDefaultRoleActors(java.lang.String in0, com.easyinsight.datafeeds.jira.jiraweb.RemoteProjectRole in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public void removeAllRoleActorsByNameAndType(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public void removeAllRoleActorsByProject(java.lang.String in0, com.easyinsight.datafeeds.jira.jiraweb.RemoteProject in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public void deleteProjectRole(java.lang.String in0, com.easyinsight.datafeeds.jira.jiraweb.RemoteProjectRole in1, boolean in2) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public void updateProjectRole(java.lang.String in0, com.easyinsight.datafeeds.jira.jiraweb.RemoteProjectRole in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteProjectRole createProjectRole(java.lang.String in0, com.easyinsight.datafeeds.jira.jiraweb.RemoteProjectRole in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public boolean isProjectRoleNameUnique(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public void addActorsToProjectRole(java.lang.String in0, java.lang.String[] in1, com.easyinsight.datafeeds.jira.jiraweb.RemoteProjectRole in2, com.easyinsight.datafeeds.jira.jiraweb.RemoteProject in3, java.lang.String in4) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public void removeActorsFromProjectRole(java.lang.String in0, java.lang.String[] in1, com.easyinsight.datafeeds.jira.jiraweb.RemoteProjectRole in2, com.easyinsight.datafeeds.jira.jiraweb.RemoteProject in3, java.lang.String in4) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public void addDefaultActorsToProjectRole(java.lang.String in0, java.lang.String[] in1, com.easyinsight.datafeeds.jira.jiraweb.RemoteProjectRole in2, java.lang.String in3) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public void removeDefaultActorsFromProjectRole(java.lang.String in0, java.lang.String[] in1, com.easyinsight.datafeeds.jira.jiraweb.RemoteProjectRole in2, java.lang.String in3) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteScheme[] getAssociatedNotificationSchemes(java.lang.String in0, com.easyinsight.datafeeds.jira.jiraweb.RemoteProjectRole in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteScheme[] getAssociatedPermissionSchemes(java.lang.String in0, com.easyinsight.datafeeds.jira.jiraweb.RemoteProjectRole in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteField[] getCustomFields(java.lang.String in0) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteComment[] getComments(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteFilter[] getFavouriteFilters(java.lang.String in0) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public void archiveVersion(java.lang.String in0, java.lang.String in1, java.lang.String in2, boolean in3) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteVersion[] getVersions(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteProject createProject(java.lang.String in0, java.lang.String in1, java.lang.String in2, java.lang.String in3, java.lang.String in4, java.lang.String in5, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionScheme in6, com.easyinsight.datafeeds.jira.jiraweb.RemoteScheme in7, com.easyinsight.datafeeds.jira.jiraweb.RemoteScheme in8) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public void addComment(java.lang.String in0, java.lang.String in1, com.easyinsight.datafeeds.jira.jiraweb.RemoteComment in2) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteField[] getFieldsForEdit(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteIssueType[] getIssueTypesForProject(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteIssueType[] getSubTaskIssueTypesForProject(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException;
    public void addUserToGroup(java.lang.String in0, com.easyinsight.datafeeds.jira.jiraweb.RemoteGroup in1, com.easyinsight.datafeeds.jira.jiraweb.RemoteUser in2) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public void removeUserFromGroup(java.lang.String in0, com.easyinsight.datafeeds.jira.jiraweb.RemoteGroup in1, com.easyinsight.datafeeds.jira.jiraweb.RemoteUser in2) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public boolean logout(java.lang.String in0) throws java.rmi.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteProject getProjectById(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteProject getProjectWithSchemesById(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public void deleteProject(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public void releaseVersion(java.lang.String in0, java.lang.String in1, com.easyinsight.datafeeds.jira.jiraweb.RemoteVersion in2) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteSecurityLevel[] getSecurityLevels(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public void deleteIssue(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteIssue createIssueWithSecurityLevel(java.lang.String in0, com.easyinsight.datafeeds.jira.jiraweb.RemoteIssue in1, long in2) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public boolean addAttachmentsToIssue(java.lang.String in0, java.lang.String in1, java.lang.String[] in2, byte[][] in3) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteAttachment[] getAttachmentsFromIssue(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public boolean hasPermissionToEditComment(java.lang.String in0, com.easyinsight.datafeeds.jira.jiraweb.RemoteComment in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteComment editComment(java.lang.String in0, com.easyinsight.datafeeds.jira.jiraweb.RemoteComment in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteField[] getFieldsForAction(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteIssue progressWorkflowAction(java.lang.String in0, java.lang.String in1, java.lang.String in2, com.easyinsight.datafeeds.jira.jiraweb.RemoteFieldValue[] in3) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteIssue getIssueById(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteWorklog addWorklogWithNewRemainingEstimate(java.lang.String in0, java.lang.String in1, com.easyinsight.datafeeds.jira.jiraweb.RemoteWorklog in2, java.lang.String in3) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteWorklog addWorklogAndAutoAdjustRemainingEstimate(java.lang.String in0, java.lang.String in1, com.easyinsight.datafeeds.jira.jiraweb.RemoteWorklog in2) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteWorklog addWorklogAndRetainRemainingEstimate(java.lang.String in0, java.lang.String in1, com.easyinsight.datafeeds.jira.jiraweb.RemoteWorklog in2) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public void deleteWorklogWithNewRemainingEstimate(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public void deleteWorklogAndAutoAdjustRemainingEstimate(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public void deleteWorklogAndRetainRemainingEstimate(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public void updateWorklogWithNewRemainingEstimate(java.lang.String in0, com.easyinsight.datafeeds.jira.jiraweb.RemoteWorklog in1, java.lang.String in2) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public void updateWorklogAndAutoAdjustRemainingEstimate(java.lang.String in0, com.easyinsight.datafeeds.jira.jiraweb.RemoteWorklog in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public void updateWorklogAndRetainRemainingEstimate(java.lang.String in0, com.easyinsight.datafeeds.jira.jiraweb.RemoteWorklog in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteWorklog[] getWorklogs(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public boolean hasPermissionToCreateWorklog(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public boolean hasPermissionToDeleteWorklog(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public boolean hasPermissionToUpdateWorklog(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteScheme[] getNotificationSchemes(java.lang.String in0) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionScheme[] getPermissionSchemes(java.lang.String in0) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionScheme createPermissionScheme(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public void deletePermissionScheme(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionScheme addPermissionTo(java.lang.String in0, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionScheme in1, com.easyinsight.datafeeds.jira.jiraweb.RemotePermission in2, com.easyinsight.datafeeds.jira.jiraweb.RemoteEntity in3) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionScheme deletePermissionFrom(java.lang.String in0, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionScheme in1, com.easyinsight.datafeeds.jira.jiraweb.RemotePermission in2, com.easyinsight.datafeeds.jira.jiraweb.RemoteEntity in3) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemotePermission[] getAllPermissions(java.lang.String in0) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public long getIssueCountForFilter(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteIssue[] getIssuesFromTextSearch(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteIssue[] getIssuesFromTextSearchWithProject(java.lang.String in0, java.lang.String[] in1, java.lang.String in2, int in3) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public void deleteUser(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteGroup updateGroup(java.lang.String in0, com.easyinsight.datafeeds.jira.jiraweb.RemoteGroup in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public void deleteGroup(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public void refreshCustomFields(java.lang.String in0) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteProject[] getProjectsNoSchemes(java.lang.String in0) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteVersion addVersion(java.lang.String in0, java.lang.String in1, com.easyinsight.datafeeds.jira.jiraweb.RemoteVersion in2) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteFilter[] getSavedFilters(java.lang.String in0) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteProject createProjectFromObject(java.lang.String in0, com.easyinsight.datafeeds.jira.jiraweb.RemoteProject in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteValidationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteScheme[] getSecuritySchemes(java.lang.String in0) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemotePermissionException, com.easyinsight.datafeeds.jira.jiraweb.RemoteAuthenticationException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
    public com.easyinsight.datafeeds.jira.jiraweb.RemoteIssue[] getIssuesFromFilter(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.easyinsight.datafeeds.jira.jiraweb.RemoteException;
}
