
/*
 * 
 */

package test.apithrottling;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.1
 * Tue Mar 31 17:20:07 MDT 2009
 * Generated source version: 2.1.1
 * 
 */
 
 /*
  * 
  */


@WebService(targetNamespace = "http://basicauth.api.easyinsight.com/", name = "BasicAuthValidatedPublish")
@XmlSeeAlso({ObjectFactory.class})

public interface BasicAuthValidatedPublish {

/*
 * 
 */

    @RequestWrapper(localName = "updateRow", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "test.apithrottling.UpdateRow")
    @ResponseWrapper(localName = "updateRowResponse", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "test.apithrottling.UpdateRowResponse")
    @WebMethod
    public void updateRow(
        @WebParam(name = "dataSourceKey", targetNamespace = "")
        java.lang.String dataSourceKey,
        @WebParam(name = "row", targetNamespace = "")
        test.apithrottling.Row row,
        @WebParam(name = "where", targetNamespace = "")
        test.apithrottling.Where where
    );

/*
 * 
 */

    @RequestWrapper(localName = "addRows", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "test.apithrottling.AddRows")
    @ResponseWrapper(localName = "addRowsResponse", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "test.apithrottling.AddRowsResponse")
    @WebMethod
    public void addRows(
        @WebParam(name = "dataSourceKey", targetNamespace = "")
        java.lang.String dataSourceKey,
        @WebParam(name = "rows", targetNamespace = "")
        java.util.List<test.apithrottling.Row> rows
    );

/*
 * 
 */

    @RequestWrapper(localName = "replaceRows", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "test.apithrottling.ReplaceRows")
    @ResponseWrapper(localName = "replaceRowsResponse", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "test.apithrottling.ReplaceRowsResponse")
    @WebMethod
    public void replaceRows(
        @WebParam(name = "dataSourceKey", targetNamespace = "")
        java.lang.String dataSourceKey,
        @WebParam(name = "rows", targetNamespace = "")
        java.util.List<test.apithrottling.Row> rows
    );

/*
 * 
 */

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "validateCredentials", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "test.apithrottling.ValidateCredentials")
    @ResponseWrapper(localName = "validateCredentialsResponse", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "test.apithrottling.ValidateCredentialsResponse")
    @WebMethod
    public boolean validateCredentials();

/*
 * 
 */

    @RequestWrapper(localName = "deleteRows", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "test.apithrottling.DeleteRows")
    @ResponseWrapper(localName = "deleteRowsResponse", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "test.apithrottling.DeleteRowsResponse")
    @WebMethod
    public void deleteRows(
        @WebParam(name = "dataSourceKey", targetNamespace = "")
        java.lang.String dataSourceKey,
        @WebParam(name = "where", targetNamespace = "")
        test.apithrottling.Where where
    );

/*
 * 
 */

    @RequestWrapper(localName = "updateRows", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "test.apithrottling.UpdateRows")
    @ResponseWrapper(localName = "updateRowsResponse", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "test.apithrottling.UpdateRowsResponse")
    @WebMethod
    public void updateRows(
        @WebParam(name = "dataSourceKey", targetNamespace = "")
        java.lang.String dataSourceKey,
        @WebParam(name = "rows", targetNamespace = "")
        java.util.List<test.apithrottling.Row> rows,
        @WebParam(name = "where", targetNamespace = "")
        test.apithrottling.Where where
    );

/*
 * 
 */

    @RequestWrapper(localName = "addRow", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "test.apithrottling.AddRow")
    @ResponseWrapper(localName = "addRowResponse", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "test.apithrottling.AddRowResponse")
    @WebMethod
    public void addRow(
        @WebParam(name = "dataSourceKey", targetNamespace = "")
        java.lang.String dataSourceKey,
        @WebParam(name = "row", targetNamespace = "")
        test.apithrottling.Row row
    );
}
