
/*
 * 
 */

package test.apithrottling;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1.1
 * Tue Mar 31 17:20:07 MDT 2009
 * Generated source version: 2.1.1
 * 
 */
 
/*
 * 
 */

@WebServiceClient(name = "BasicAuthValidatingPublishServiceService", 
                  wsdlLocation = "file:/C:/Users/abaldwin/Documents/EasyInsight/code/java/src/test/apithrottling/ValidatedPublishBasic.wsdl",
                  targetNamespace = "http://basicauth.api.easyinsight.com/") 
public class BasicAuthValidatingPublishServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://basicauth.api.easyinsight.com/", "BasicAuthValidatingPublishServiceService");
    public final static QName BasicAuthValidatingPublishServicePort = new QName("http://basicauth.api.easyinsight.com/", "BasicAuthValidatingPublishServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/abaldwin/Documents/EasyInsight/code/java/src/test/apithrottling/ValidatedPublishBasic.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/C:/Users/abaldwin/Documents/EasyInsight/code/java/src/test/apithrottling/ValidatedPublishBasic.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public BasicAuthValidatingPublishServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BasicAuthValidatingPublishServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BasicAuthValidatingPublishServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns BasicAuthValidatedPublish
     */
    @WebEndpoint(name = "BasicAuthValidatingPublishServicePort")
    public BasicAuthValidatedPublish getBasicAuthValidatingPublishServicePort() {
        return super.getPort(BasicAuthValidatingPublishServicePort, BasicAuthValidatedPublish.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BasicAuthValidatedPublish
     */
    @WebEndpoint(name = "BasicAuthValidatingPublishServicePort")
    public BasicAuthValidatedPublish getBasicAuthValidatingPublishServicePort(WebServiceFeature... features) {
        return super.getPort(BasicAuthValidatingPublishServicePort, BasicAuthValidatedPublish.class, features);
    }

}
