
package com.clarity.books.service.api;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "AlreadyExists", targetNamespace = "http://api.service.books/")
public class AlreadyExists_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AlreadyExists faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public AlreadyExists_Exception(String message, AlreadyExists faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public AlreadyExists_Exception(String message, AlreadyExists faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.clarity.books.service.api.AlreadyExists
     */
    public AlreadyExists getFaultInfo() {
        return faultInfo;
    }

}
