
package com.clarity.books.service.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BooksApiV1Service", targetNamespace = "http://api.service.books/", wsdlLocation = "https://www.clarityaccounting.com/api/v1?wsdl")
public class BooksApiV1Service
    extends Service
{

    private final static URL BOOKSAPIV1SERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("https://www.clarityaccounting.com/api/v1?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        BOOKSAPIV1SERVICE_WSDL_LOCATION = url;
    }

    public BooksApiV1Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BooksApiV1Service() {
        super(BOOKSAPIV1SERVICE_WSDL_LOCATION, new QName("http://api.service.books/", "BooksApiV1Service"));
    }

    /**
     * 
     * @return
     *     returns BooksApiV1
     */
    @WebEndpoint(name = "BooksApiV1Port")
    public BooksApiV1 getBooksApiV1Port() {
        return (BooksApiV1)super.getPort(new QName("http://api.service.books/", "BooksApiV1Port"), BooksApiV1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BooksApiV1
     */
    @WebEndpoint(name = "BooksApiV1Port")
    public BooksApiV1 getBooksApiV1Port(WebServiceFeature... features) {
        return (BooksApiV1)super.getPort(new QName("http://api.service.books/", "BooksApiV1Port"), BooksApiV1.class, features);
    }

}
