
package com.clarity.books.service.api;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ConcurrentChangeException", targetNamespace = "http://api.service.books/")
public class ConcurrentChangeException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ConcurrentChangeException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ConcurrentChangeException_Exception(String message, ConcurrentChangeException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ConcurrentChangeException_Exception(String message, ConcurrentChangeException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.clarity.books.service.api.ConcurrentChangeException
     */
    public ConcurrentChangeException getFaultInfo() {
        return faultInfo;
    }

}
