
package com.easyinsight.rowutil.transactional;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BasicAuthTransactionalLoadAPIService", targetNamespace = "http://v2.api.easyinsight.com/", wsdlLocation = "https://www.easy-insight.com/app/services/EITransactionalLoad?wsdl")
public class BasicAuthTransactionalLoadAPIService
    extends Service
{

    private final static URL BASICAUTHTRANSACTIONALLOADAPISERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("https://www.easy-insight.com/app/services/EITransactionalLoad?wsdl");
            
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        BASICAUTHTRANSACTIONALLOADAPISERVICE_WSDL_LOCATION = url;
    }

    public BasicAuthTransactionalLoadAPIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BasicAuthTransactionalLoadAPIService() {
        super(BASICAUTHTRANSACTIONALLOADAPISERVICE_WSDL_LOCATION, new QName("http://v2.api.easyinsight.com/", "BasicAuthTransactionalLoadAPIService"));
    }

    /**
     * 
     * @return
     *     returns EITransactionalLoad
     */
    @WebEndpoint(name = "BasicAuthTransactionalLoadAPIPort")
    public EITransactionalLoad getBasicAuthTransactionalLoadAPIPort() {
        return (EITransactionalLoad)super.getPort(new QName("http://v2.api.easyinsight.com/", "BasicAuthTransactionalLoadAPIPort"), EITransactionalLoad.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EITransactionalLoad
     */
    @WebEndpoint(name = "BasicAuthTransactionalLoadAPIPort")
    public EITransactionalLoad getBasicAuthTransactionalLoadAPIPort(WebServiceFeature... features) {
        return (EITransactionalLoad)super.getPort(new QName("http://v2.api.easyinsight.com/", "BasicAuthTransactionalLoadAPIPort"), EITransactionalLoad.class, features);
    }

}
