
package com.easyinsight.rowutil.transactional;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EITransactionalLoad", targetNamespace = "http://v2.api.easyinsight.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EITransactionalLoad {


    /**
     * 
     * @param transactionID
     * @param rows
     */
    @WebMethod
    @RequestWrapper(localName = "loadRows", targetNamespace = "http://v2.api.easyinsight.com/", className = "com.easyinsight.rowutil.transactional.LoadRows")
    @ResponseWrapper(localName = "loadRowsResponse", targetNamespace = "http://v2.api.easyinsight.com/", className = "com.easyinsight.rowutil.transactional.LoadRowsResponse")
    public void loadRows(
        @WebParam(name = "rows", targetNamespace = "")
        List<Row> rows,
        @WebParam(name = "transactionID", targetNamespace = "")
        String transactionID);

    /**
     * 
     * @param transactionID
     */
    @WebMethod
    @RequestWrapper(localName = "rollback", targetNamespace = "http://v2.api.easyinsight.com/", className = "com.easyinsight.rowutil.transactional.Rollback")
    @ResponseWrapper(localName = "rollbackResponse", targetNamespace = "http://v2.api.easyinsight.com/", className = "com.easyinsight.rowutil.transactional.RollbackResponse")
    public void rollback(
        @WebParam(name = "transactionID", targetNamespace = "")
        String transactionID);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateCredentials", targetNamespace = "http://v2.api.easyinsight.com/", className = "com.easyinsight.rowutil.transactional.ValidateCredentials")
    @ResponseWrapper(localName = "validateCredentialsResponse", targetNamespace = "http://v2.api.easyinsight.com/", className = "com.easyinsight.rowutil.transactional.ValidateCredentialsResponse")
    public boolean validateCredentials();

    /**
     * 
     * @param transactionOperation
     * @param changeDataSourceToMatch
     * @param dataSourceName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "beginTransaction", targetNamespace = "http://v2.api.easyinsight.com/", className = "com.easyinsight.rowutil.transactional.BeginTransaction")
    @ResponseWrapper(localName = "beginTransactionResponse", targetNamespace = "http://v2.api.easyinsight.com/", className = "com.easyinsight.rowutil.transactional.BeginTransactionResponse")
    public String beginTransaction(
        @WebParam(name = "dataSourceName", targetNamespace = "")
        String dataSourceName,
        @WebParam(name = "transactionOperation", targetNamespace = "")
        boolean transactionOperation,
        @WebParam(name = "changeDataSourceToMatch", targetNamespace = "")
        boolean changeDataSourceToMatch);

    /**
     * 
     * @param transactionID
     * @return
     *     returns com.easyinsight.rowutil.transactional.CommitResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "commit", targetNamespace = "http://v2.api.easyinsight.com/", className = "com.easyinsight.rowutil.transactional.Commit")
    @ResponseWrapper(localName = "commitResponse", targetNamespace = "http://v2.api.easyinsight.com/", className = "com.easyinsight.rowutil.transactional.CommitResponse")
    public CommitResult commit(
        @WebParam(name = "transactionID", targetNamespace = "")
        String transactionID);

}
