
package com.easyinsight.rowutil.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BasicAuthUncheckedPublishServiceService", targetNamespace = "http://basicauth.api.easyinsight.com/", wsdlLocation = "https://www.easy-insight.com/app/services/UncheckedPublishBasic?wsdl")
public class BasicAuthUncheckedPublishServiceService
    extends Service
{

    private final static URL BASICAUTHUNCHECKEDPUBLISHSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.easyinsight.rowutil.webservice.BasicAuthUncheckedPublishServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.easyinsight.rowutil.webservice.BasicAuthUncheckedPublishServiceService.class.getResource(".");
            url = new URL(baseUrl, "https://www.easy-insight.com/app/services/UncheckedPublishBasic?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://www.easy-insight.com/app/services/UncheckedPublishBasic?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BASICAUTHUNCHECKEDPUBLISHSERVICESERVICE_WSDL_LOCATION = url;
    }

    public BasicAuthUncheckedPublishServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BasicAuthUncheckedPublishServiceService() {
        super(BASICAUTHUNCHECKEDPUBLISHSERVICESERVICE_WSDL_LOCATION, new QName("http://basicauth.api.easyinsight.com/", "BasicAuthUncheckedPublishServiceService"));
    }

    /**
     * 
     * @return
     *     returns BasicAuthUncheckedPublish
     */
    @WebEndpoint(name = "BasicAuthUncheckedPublishServicePort")
    public BasicAuthUncheckedPublish getBasicAuthUncheckedPublishServicePort() {
        return super.getPort(new QName("http://basicauth.api.easyinsight.com/", "BasicAuthUncheckedPublishServicePort"), BasicAuthUncheckedPublish.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BasicAuthUncheckedPublish
     */
    @WebEndpoint(name = "BasicAuthUncheckedPublishServicePort")
    public BasicAuthUncheckedPublish getBasicAuthUncheckedPublishServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://basicauth.api.easyinsight.com/", "BasicAuthUncheckedPublishServicePort"), BasicAuthUncheckedPublish.class, features);
    }

}
