
package com.easyinsight.rowutil.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BasicAuthUncheckedPublish", targetNamespace = "http://basicauth.api.easyinsight.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BasicAuthUncheckedPublish {


    /**
     * 
     * @param where
     * @param dataSourceName
     * @param row
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateRow", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "com.easyinsight.rowutil.webservice.UpdateRow")
    @ResponseWrapper(localName = "updateRowResponse", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "com.easyinsight.rowutil.webservice.UpdateRowResponse")
    public String updateRow(
        @WebParam(name = "dataSourceName", targetNamespace = "")
        String dataSourceName,
        @WebParam(name = "row", targetNamespace = "")
        Row row,
        @WebParam(name = "where", targetNamespace = "")
        Where where);

    /**
     * 
     * @param dataSourceName
     * @param rows
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addRows", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "com.easyinsight.rowutil.webservice.AddRows")
    @ResponseWrapper(localName = "addRowsResponse", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "com.easyinsight.rowutil.webservice.AddRowsResponse")
    public String addRows(
        @WebParam(name = "dataSourceName", targetNamespace = "")
        String dataSourceName,
        @WebParam(name = "rows", targetNamespace = "")
        List<Row> rows);

    /**
     * 
     * @param dataSourceName
     * @param rows
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "replaceRows", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "com.easyinsight.rowutil.webservice.ReplaceRows")
    @ResponseWrapper(localName = "replaceRowsResponse", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "com.easyinsight.rowutil.webservice.ReplaceRowsResponse")
    public String replaceRows(
        @WebParam(name = "dataSourceName", targetNamespace = "")
        String dataSourceName,
        @WebParam(name = "rows", targetNamespace = "")
        List<Row> rows);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateCredentials", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "com.easyinsight.rowutil.webservice.ValidateCredentials")
    @ResponseWrapper(localName = "validateCredentialsResponse", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "com.easyinsight.rowutil.webservice.ValidateCredentialsResponse")
    public boolean validateCredentials();

    /**
     * 
     * @param where
     * @param dataSourceName
     */
    @WebMethod
    @RequestWrapper(localName = "deleteRows", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "com.easyinsight.rowutil.webservice.DeleteRows")
    @ResponseWrapper(localName = "deleteRowsResponse", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "com.easyinsight.rowutil.webservice.DeleteRowsResponse")
    public void deleteRows(
        @WebParam(name = "dataSourceName", targetNamespace = "")
        String dataSourceName,
        @WebParam(name = "where", targetNamespace = "")
        Where where);

    /**
     * 
     * @param where
     * @param dataSourceName
     * @param rows
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateRows", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "com.easyinsight.rowutil.webservice.UpdateRows")
    @ResponseWrapper(localName = "updateRowsResponse", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "com.easyinsight.rowutil.webservice.UpdateRowsResponse")
    public String updateRows(
        @WebParam(name = "dataSourceName", targetNamespace = "")
        String dataSourceName,
        @WebParam(name = "rows", targetNamespace = "")
        List<Row> rows,
        @WebParam(name = "where", targetNamespace = "")
        Where where);

    /**
     * 
     * @param dataSourceName
     * @param row
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addRow", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "com.easyinsight.rowutil.webservice.AddRow")
    @ResponseWrapper(localName = "addRowResponse", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "com.easyinsight.rowutil.webservice.AddRowResponse")
    public String addRow(
        @WebParam(name = "dataSourceName", targetNamespace = "")
        String dataSourceName,
        @WebParam(name = "row", targetNamespace = "")
        Row row);

    /**
     * 
     * @param dataSourceKey
     */
    @WebMethod
    @RequestWrapper(localName = "disableUnchecked", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "com.easyinsight.rowutil.webservice.DisableUnchecked")
    @ResponseWrapper(localName = "disableUncheckedResponse", targetNamespace = "http://basicauth.api.easyinsight.com/", className = "com.easyinsight.rowutil.webservice.DisableUncheckedResponse")
    public void disableUnchecked(
        @WebParam(name = "dataSourceKey", targetNamespace = "")
        String dataSourceKey);

}
