package com.easyinsight.database;

import org.apache.commons.dbcp.*;
import org.apache.commons.pool.impl.GenericObjectPool;
import org.hibernate.SessionFactory;
import org.hibernate.Session;
import org.hibernate.StatelessSession;
import org.hibernate.cfg.AnnotationConfiguration;

import javax.sql.DataSource;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.text.MessageFormat;

import com.easyinsight.logging.LogClass;
import com.easyinsight.config.ConfigLoader;

/**
 * User: jboe
 * Date: Jan 2, 2008
 * Time: 12:50:36 PM
 */
public class Database {

    private DataSource dataSource;
    private SessionFactory sessionFactory;
    private static Database instance;
    private GenericObjectPool connectionPool;

    private String urlTemplate = "jdbc:mysql://{0}:{1}/{2}";

    private Database(String host, String port, String databaseName, String userName, String password) {
        dataSource = setupDataSource(host, port, databaseName, userName, password);
        try {
            AnnotationConfiguration configuration = new AnnotationConfiguration().configure();
            String url = MessageFormat.format(urlTemplate, host, port, databaseName);
            configuration.setProperty("connection.url", url);
            configuration.setProperty("connection.username", userName);
            configuration.setProperty("connection.password", password);
            sessionFactory = configuration.buildSessionFactory();
        } catch (Throwable e) {
            LogClass.error(e);
        }
    }

    public static Database instance() {
        return instance;
    }

    public static Database create(String host, String port, String databaseName, String userName, String password) {
        return new Database(host, port, databaseName, userName, password);
    }

    public static void initialize() {
        instance = new Database(ConfigLoader.instance().getDatabaseHost(), ConfigLoader.instance().getDatabasePort(),
                ConfigLoader.instance().getDatabaseName(), ConfigLoader.instance().getDatabaseUserName(),
                ConfigLoader.instance().getDatabasePassword());
    }

    public Session createSession() {
        return sessionFactory.openSession();
    }

    public Session createSession(Connection conn) {
        return sessionFactory.openSession(conn);
    }

    public StatelessSession createStatelessSession() {
        return sessionFactory.openStatelessSession();
    }

    public Connection getConnection() {
        try {
            return dataSource.getConnection();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public void closeConnection(Connection conn) {
        try {
            conn.close();
        } catch (SQLException e) {
            LogClass.error(e);
            throw new RuntimeException(e);
        }
    }

    private DataSource setupDataSource(String host, String port, String databaseName, String userName, String password) {
        connectionPool = new GenericObjectPool(null);

        connectionPool.setMinIdle(5);
        connectionPool.setMaxActive(20);

        String url = MessageFormat.format(urlTemplate, host, port, databaseName);

        ConnectionFactory connectionFactory =
        	new DriverManagerConnectionFactory(url, userName, password);

       new PoolableConnectionFactory(connectionFactory,connectionPool,null,null,false,true);

        return new PoolingDataSource(connectionPool);
    }

    public long getAutoGenKey(Statement stmt) {
        try {
            ResultSet rs = stmt.getGeneratedKeys();
            if (rs.next()) {
                return rs.getLong(1);
            } else {
                throw new RuntimeException("No entry found in result set for autogenerated key");
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public int getActiveConnections() {
        return connectionPool.getNumActive();
    }

    public int getIdleConnections() {
        return connectionPool.getNumIdle();
    }
}
