
package com.easyinsight.rowutil.v3web;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BasicAuthEIV3APIService", targetNamespace = "http://v3.api.easyinsight.com/", wsdlLocation = "https://www.easy-insight.com/app/services/EIDataV3?wsdl")
public class BasicAuthEIV3APIService
    extends Service
{

    private final static URL BASICAUTHEIV3APISERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("https://www.easy-insight.com/app/services/EIDataV3?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        BASICAUTHEIV3APISERVICE_WSDL_LOCATION = url;
    }

    public BasicAuthEIV3APIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BasicAuthEIV3APIService() {
        super(BASICAUTHEIV3APISERVICE_WSDL_LOCATION, new QName("http://v3.api.easyinsight.com/", "BasicAuthEIV3APIService"));
    }

    /**
     * 
     * @return
     *     returns EIDataV3
     */
    @WebEndpoint(name = "BasicAuthEIV3APIPort")
    public EIDataV3 getBasicAuthEIV3APIPort() {
        return (EIDataV3)super.getPort(new QName("http://v3.api.easyinsight.com/", "BasicAuthEIV3APIPort"), EIDataV3.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EIDataV3
     */
    @WebEndpoint(name = "BasicAuthEIV3APIPort")
    public EIDataV3 getBasicAuthEIV3APIPort(WebServiceFeature... features) {
        return (EIDataV3)super.getPort(new QName("http://v3.api.easyinsight.com/", "BasicAuthEIV3APIPort"), EIDataV3.class, features);
    }

}
