
package com.easyinsight.rowutil.v3web;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EIDataV3", targetNamespace = "http://v3.api.easyinsight.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EIDataV3 {


    /**
     * 
     * @param dataSourceName
     * @return
     *     returns com.easyinsight.rowutil.v3web.DataSourceInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSourceInfo", targetNamespace = "http://v3.api.easyinsight.com/", className = "com.easyinsight.rowutil.v3web.GetSourceInfo")
    @ResponseWrapper(localName = "getSourceInfoResponse", targetNamespace = "http://v3.api.easyinsight.com/", className = "com.easyinsight.rowutil.v3web.GetSourceInfoResponse")
    public DataSourceInfo getSourceInfo(
        @WebParam(name = "dataSourceName", targetNamespace = "")
        String dataSourceName);

    /**
     * 
     * @param where
     * @param dataSourceName
     */
    @WebMethod
    @RequestWrapper(localName = "deleteRows", targetNamespace = "http://v3.api.easyinsight.com/", className = "com.easyinsight.rowutil.v3web.DeleteRows")
    @ResponseWrapper(localName = "deleteRowsResponse", targetNamespace = "http://v3.api.easyinsight.com/", className = "com.easyinsight.rowutil.v3web.DeleteRowsResponse")
    public void deleteRows(
        @WebParam(name = "dataSourceName", targetNamespace = "")
        String dataSourceName,
        @WebParam(name = "where", targetNamespace = "")
        Where where);

    /**
     * 
     * @param transactionID
     * @param rows
     */
    @WebMethod
    @RequestWrapper(localName = "loadRows", targetNamespace = "http://v3.api.easyinsight.com/", className = "com.easyinsight.rowutil.v3web.LoadRows")
    @ResponseWrapper(localName = "loadRowsResponse", targetNamespace = "http://v3.api.easyinsight.com/", className = "com.easyinsight.rowutil.v3web.LoadRowsResponse")
    public void loadRows(
        @WebParam(name = "rows", targetNamespace = "")
        List<Row> rows,
        @WebParam(name = "transactionID", targetNamespace = "")
        String transactionID);

    /**
     * 
     * @param transactionID
     * @return
     *     returns com.easyinsight.rowutil.v3web.CommitResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "commit", targetNamespace = "http://v3.api.easyinsight.com/", className = "com.easyinsight.rowutil.v3web.Commit")
    @ResponseWrapper(localName = "commitResponse", targetNamespace = "http://v3.api.easyinsight.com/", className = "com.easyinsight.rowutil.v3web.CommitResponse")
    public CommitResult commit(
        @WebParam(name = "transactionID", targetNamespace = "")
        String transactionID);

    /**
     * 
     * @param changeDataSourceToMatch
     * @param dataSourceName
     * @param rows
     */
    @WebMethod
    @RequestWrapper(localName = "addRows", targetNamespace = "http://v3.api.easyinsight.com/", className = "com.easyinsight.rowutil.v3web.AddRows")
    @ResponseWrapper(localName = "addRowsResponse", targetNamespace = "http://v3.api.easyinsight.com/", className = "com.easyinsight.rowutil.v3web.AddRowsResponse")
    public void addRows(
        @WebParam(name = "dataSourceName", targetNamespace = "")
        String dataSourceName,
        @WebParam(name = "rows", targetNamespace = "")
        List<Row> rows,
        @WebParam(name = "changeDataSourceToMatch", targetNamespace = "")
        boolean changeDataSourceToMatch);

    /**
     * 
     * @param transactionOperation
     * @param changeDataSourceToMatch
     * @param dataSourceName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "beginTransaction", targetNamespace = "http://v3.api.easyinsight.com/", className = "com.easyinsight.rowutil.v3web.BeginTransaction")
    @ResponseWrapper(localName = "beginTransactionResponse", targetNamespace = "http://v3.api.easyinsight.com/", className = "com.easyinsight.rowutil.v3web.BeginTransactionResponse")
    public String beginTransaction(
        @WebParam(name = "dataSourceName", targetNamespace = "")
        String dataSourceName,
        @WebParam(name = "transactionOperation", targetNamespace = "")
        boolean transactionOperation,
        @WebParam(name = "changeDataSourceToMatch", targetNamespace = "")
        boolean changeDataSourceToMatch);

    /**
     * 
     * @param changeDataSourceToMatch
     * @param dataSourceName
     * @param row
     */
    @WebMethod
    @RequestWrapper(localName = "addRow", targetNamespace = "http://v3.api.easyinsight.com/", className = "com.easyinsight.rowutil.v3web.AddRow")
    @ResponseWrapper(localName = "addRowResponse", targetNamespace = "http://v3.api.easyinsight.com/", className = "com.easyinsight.rowutil.v3web.AddRowResponse")
    public void addRow(
        @WebParam(name = "dataSourceName", targetNamespace = "")
        String dataSourceName,
        @WebParam(name = "row", targetNamespace = "")
        Row row,
        @WebParam(name = "changeDataSourceToMatch", targetNamespace = "")
        boolean changeDataSourceToMatch);

    /**
     * 
     * @param transactionID
     */
    @WebMethod
    @RequestWrapper(localName = "rollback", targetNamespace = "http://v3.api.easyinsight.com/", className = "com.easyinsight.rowutil.v3web.Rollback")
    @ResponseWrapper(localName = "rollbackResponse", targetNamespace = "http://v3.api.easyinsight.com/", className = "com.easyinsight.rowutil.v3web.RollbackResponse")
    public void rollback(
        @WebParam(name = "transactionID", targetNamespace = "")
        String transactionID);

    /**
     * 
     * @param changeDataSourceToMatch
     * @param dataSourceName
     * @param rows
     */
    @WebMethod
    @RequestWrapper(localName = "replaceRows", targetNamespace = "http://v3.api.easyinsight.com/", className = "com.easyinsight.rowutil.v3web.ReplaceRows")
    @ResponseWrapper(localName = "replaceRowsResponse", targetNamespace = "http://v3.api.easyinsight.com/", className = "com.easyinsight.rowutil.v3web.ReplaceRowsResponse")
    public void replaceRows(
        @WebParam(name = "dataSourceName", targetNamespace = "")
        String dataSourceName,
        @WebParam(name = "rows", targetNamespace = "")
        List<Row> rows,
        @WebParam(name = "changeDataSourceToMatch", targetNamespace = "")
        boolean changeDataSourceToMatch);

    /**
     * 
     * @param externalConnectionKey
     * @param dataSources
     * @param connections
     * @param dataSourceName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "defineCompositeDataSource", targetNamespace = "http://v3.api.easyinsight.com/", className = "com.easyinsight.rowutil.v3web.DefineCompositeDataSource")
    @ResponseWrapper(localName = "defineCompositeDataSourceResponse", targetNamespace = "http://v3.api.easyinsight.com/", className = "com.easyinsight.rowutil.v3web.DefineCompositeDataSourceResponse")
    public String defineCompositeDataSource(
        @WebParam(name = "dataSources", targetNamespace = "")
        List<String> dataSources,
        @WebParam(name = "connections", targetNamespace = "")
        List<DataSourceConnection> connections,
        @WebParam(name = "dataSourceName", targetNamespace = "")
        String dataSourceName,
        @WebParam(name = "externalConnectionKey", targetNamespace = "")
        String externalConnectionKey);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateCredentials", targetNamespace = "http://v3.api.easyinsight.com/", className = "com.easyinsight.rowutil.v3web.ValidateCredentials")
    @ResponseWrapper(localName = "validateCredentialsResponse", targetNamespace = "http://v3.api.easyinsight.com/", className = "com.easyinsight.rowutil.v3web.ValidateCredentialsResponse")
    public boolean validateCredentials();

    /**
     * 
     * @param changeDataSourceToMatch
     * @param where
     * @param dataSourceName
     * @param row
     */
    @WebMethod
    @RequestWrapper(localName = "updateRow", targetNamespace = "http://v3.api.easyinsight.com/", className = "com.easyinsight.rowutil.v3web.UpdateRow")
    @ResponseWrapper(localName = "updateRowResponse", targetNamespace = "http://v3.api.easyinsight.com/", className = "com.easyinsight.rowutil.v3web.UpdateRowResponse")
    public void updateRow(
        @WebParam(name = "dataSourceName", targetNamespace = "")
        String dataSourceName,
        @WebParam(name = "row", targetNamespace = "")
        Row row,
        @WebParam(name = "where", targetNamespace = "")
        Where where,
        @WebParam(name = "changeDataSourceToMatch", targetNamespace = "")
        boolean changeDataSourceToMatch);

    /**
     * 
     * @param externalConnectionKey
     * @param dataSourceName
     * @param fields
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "defineDataSource", targetNamespace = "http://v3.api.easyinsight.com/", className = "com.easyinsight.rowutil.v3web.DefineDataSource")
    @ResponseWrapper(localName = "defineDataSourceResponse", targetNamespace = "http://v3.api.easyinsight.com/", className = "com.easyinsight.rowutil.v3web.DefineDataSourceResponse")
    public String defineDataSource(
        @WebParam(name = "dataSourceName", targetNamespace = "")
        String dataSourceName,
        @WebParam(name = "fields", targetNamespace = "")
        List<FieldDefinition> fields,
        @WebParam(name = "externalConnectionKey", targetNamespace = "")
        String externalConnectionKey);

    /**
     * 
     * @param changeDataSourceToMatch
     * @param where
     * @param dataSourceName
     * @param rows
     */
    @WebMethod
    @RequestWrapper(localName = "updateRows", targetNamespace = "http://v3.api.easyinsight.com/", className = "com.easyinsight.rowutil.v3web.UpdateRows")
    @ResponseWrapper(localName = "updateRowsResponse", targetNamespace = "http://v3.api.easyinsight.com/", className = "com.easyinsight.rowutil.v3web.UpdateRowsResponse")
    public void updateRows(
        @WebParam(name = "dataSourceName", targetNamespace = "")
        String dataSourceName,
        @WebParam(name = "rows", targetNamespace = "")
        List<Row> rows,
        @WebParam(name = "where", targetNamespace = "")
        Where where,
        @WebParam(name = "changeDataSourceToMatch", targetNamespace = "")
        boolean changeDataSourceToMatch);

}
