
package com.easyinsight.client.marketo;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.1
 * Wed Mar 17 14:42:09 MDT 2010
 * Generated source version: 2.1.1
 * 
 */

public final class MktowsPort_MktowsApiSoapPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.marketo.com/mktows/", "MktMktowsApiService");

    private MktowsPort_MktowsApiSoapPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = MktMktowsApiService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MktMktowsApiService ss = new MktMktowsApiService(wsdlURL, SERVICE_NAME);
        MktowsPort port = ss.getMktowsApiSoapPort();  
        
        {
        System.out.println("Invoking listOperation...");
        com.easyinsight.client.marketo.ParamsListOperation _listOperation_paramsListOperation = null;
        com.easyinsight.client.marketo.SuccessListOperation _listOperation__return = port.listOperation(_listOperation_paramsListOperation);
        System.out.println("listOperation.result=" + _listOperation__return);


        }
        {
        System.out.println("Invoking syncMultipleLeads...");
        com.easyinsight.client.marketo.ParamsSyncMultipleLeads _syncMultipleLeads_paramsSyncMultipleLeads = null;
        com.easyinsight.client.marketo.SuccessSyncMultipleLeads _syncMultipleLeads__return = port.syncMultipleLeads(_syncMultipleLeads_paramsSyncMultipleLeads);
        System.out.println("syncMultipleLeads.result=" + _syncMultipleLeads__return);


        }
        {
        System.out.println("Invoking syncLead...");
        com.easyinsight.client.marketo.ParamsSyncLead _syncLead_paramsSyncLead = null;
        com.easyinsight.client.marketo.SuccessSyncLead _syncLead__return = port.syncLead(_syncLead_paramsSyncLead);
        System.out.println("syncLead.result=" + _syncLead__return);


        }
        {
        System.out.println("Invoking getLead...");
        com.easyinsight.client.marketo.ParamsGetLead _getLead_paramsGetLead = null;
        com.easyinsight.client.marketo.SuccessGetLead _getLead__return = port.getLead(_getLead_paramsGetLead);
        System.out.println("getLead.result=" + _getLead__return);


        }
        {
        System.out.println("Invoking getLeadChanges...");
        com.easyinsight.client.marketo.ParamsGetLeadChanges _getLeadChanges_paramsGetLeadChanges = null;
        com.easyinsight.client.marketo.SuccessGetLeadChanges _getLeadChanges__return = port.getLeadChanges(_getLeadChanges_paramsGetLeadChanges);
        System.out.println("getLeadChanges.result=" + _getLeadChanges__return);


        }
        {
        System.out.println("Invoking requestCampaign...");
        com.easyinsight.client.marketo.ParamsRequestCampaign _requestCampaign_paramsRequestCampaign = null;
        com.easyinsight.client.marketo.SuccessRequestCampaign _requestCampaign__return = port.requestCampaign(_requestCampaign_paramsRequestCampaign);
        System.out.println("requestCampaign.result=" + _requestCampaign__return);


        }
        {
        System.out.println("Invoking getMultipleLeads...");
        com.easyinsight.client.marketo.ParamsGetMultipleLeads _getMultipleLeads_paramsGetMultipleLeads = null;
        com.easyinsight.client.marketo.SuccessGetMultipleLeads _getMultipleLeads__return = port.getMultipleLeads(_getMultipleLeads_paramsGetMultipleLeads);
        System.out.println("getMultipleLeads.result=" + _getMultipleLeads__return);


        }
        {
        System.out.println("Invoking getCampaignsForSource...");
        com.easyinsight.client.marketo.ParamsGetCampaignsForSource _getCampaignsForSource_paramsGetCampaignsForSource = null;
        com.easyinsight.client.marketo.SuccessGetCampaignsForSource _getCampaignsForSource__return = port.getCampaignsForSource(_getCampaignsForSource_paramsGetCampaignsForSource);
        System.out.println("getCampaignsForSource.result=" + _getCampaignsForSource__return);


        }
        {
        System.out.println("Invoking getLeadActivity...");
        com.easyinsight.client.marketo.ParamsGetLeadActivity _getLeadActivity_paramsGetLeadActivity = null;
        com.easyinsight.client.marketo.SuccessGetLeadActivity _getLeadActivity__return = port.getLeadActivity(_getLeadActivity_paramsGetLeadActivity);
        System.out.println("getLeadActivity.result=" + _getLeadActivity__return);


        }

        System.exit(0);
    }

}
