
/*
 * 
 */

package com.easyinsight.client.marketo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.1
 * Wed Mar 17 14:42:09 MDT 2010
 * Generated source version: 2.1.1
 * 
 */
 
 /*
  * 
  */


@WebService(targetNamespace = "http://www.marketo.com/mktows/", name = "MktowsPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)

public interface MktowsPort {

/*
 * 
 */

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "successListOperation", targetNamespace = "http://www.marketo.com/mktows/", partName = "successListOperation")
    @WebMethod(action = "http://www.marketo.com/mktows/listOperation")
    public SuccessListOperation listOperation(
        @WebParam(partName = "paramsListOperation", name = "paramsListOperation", targetNamespace = "http://www.marketo.com/mktows/")
        ParamsListOperation paramsListOperation
    );

/*
 * 
 */

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "successSyncMultipleLeads", targetNamespace = "http://www.marketo.com/mktows/", partName = "successSyncMultipleLeads")
    @WebMethod(action = "http://www.marketo.com/mktows/syncMultipleLeads")
    public SuccessSyncMultipleLeads syncMultipleLeads(
        @WebParam(partName = "paramsSyncMultipleLeads", name = "paramsSyncMultipleLeads", targetNamespace = "http://www.marketo.com/mktows/")
        ParamsSyncMultipleLeads paramsSyncMultipleLeads
    );

/*
 * 
 */

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "successSyncLead", targetNamespace = "http://www.marketo.com/mktows/", partName = "successSyncLead")
    @WebMethod(action = "http://www.marketo.com/mktows/syncLead")
    public SuccessSyncLead syncLead(
        @WebParam(partName = "paramsSyncLead", name = "paramsSyncLead", targetNamespace = "http://www.marketo.com/mktows/")
        ParamsSyncLead paramsSyncLead
    );

/*
 * 
 */

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "successGetLead", targetNamespace = "http://www.marketo.com/mktows/", partName = "successGetLead")
    @WebMethod(action = "http://www.marketo.com/mktows/getLead")
    public SuccessGetLead getLead(
        @WebParam(partName = "paramsGetLead", name = "paramsGetLead", targetNamespace = "http://www.marketo.com/mktows/")
        ParamsGetLead paramsGetLead
    );

/*
 * 
 */

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "successGetLeadChanges", targetNamespace = "http://www.marketo.com/mktows/", partName = "successGetLeadChanges")
    @WebMethod(action = "http://www.marketo.com/mktows/getLeadChanges")
    public SuccessGetLeadChanges getLeadChanges(
        @WebParam(partName = "paramsGetLeadChanges", name = "paramsGetLeadChanges", targetNamespace = "http://www.marketo.com/mktows/")
        ParamsGetLeadChanges paramsGetLeadChanges
    );

/*
 * 
 */

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "successRequestCampaign", targetNamespace = "http://www.marketo.com/mktows/", partName = "successRequestCampaign")
    @WebMethod(action = "http://www.marketo.com/mktows/requestCampaign")
    public SuccessRequestCampaign requestCampaign(
        @WebParam(partName = "paramsRequestCampaign", name = "paramsRequestCampaign", targetNamespace = "http://www.marketo.com/mktows/")
        ParamsRequestCampaign paramsRequestCampaign
    );

/*
 * 
 */

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "successGetMultipleLeads", targetNamespace = "http://www.marketo.com/mktows/", partName = "successGetMultipleLeads")
    @WebMethod(action = "http://www.marketo.com/mktows/getMultipleLeads")
    public SuccessGetMultipleLeads getMultipleLeads(
        @WebParam(partName = "paramsGetMultipleLeads", name = "paramsGetMultipleLeads", targetNamespace = "http://www.marketo.com/mktows/")
        ParamsGetMultipleLeads paramsGetMultipleLeads
    );

/*
 * 
 */

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "successGetCampaignsForSource", targetNamespace = "http://www.marketo.com/mktows/", partName = "successGetCampaignsForSource")
    @WebMethod(action = "http://www.marketo.com/mktows/getCampaignsForSource")
    public SuccessGetCampaignsForSource getCampaignsForSource(
        @WebParam(partName = "paramsGetCampaignsForSource", name = "paramsGetCampaignsForSource", targetNamespace = "http://www.marketo.com/mktows/")
        ParamsGetCampaignsForSource paramsGetCampaignsForSource
    );

/*
 * 
 */

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "successGetLeadActivity", targetNamespace = "http://www.marketo.com/mktows/", partName = "successGetLeadActivity")
    @WebMethod(action = "http://www.marketo.com/mktows/getLeadActivity")
    public SuccessGetLeadActivity getLeadActivity(
        @WebParam(partName = "paramsGetLeadActivity", name = "paramsGetLeadActivity", targetNamespace = "http://www.marketo.com/mktows/")
        ParamsGetLeadActivity paramsGetLeadActivity
    );
}
