package com.easyinsight.map.util
{
import mx.collections.ArrayCollection;

public class MapLocationLookup
	{
		private static var usAliasMap:Object = new Object();
		private static var worldAliasMap:Object = new Object();
		
		public function MapLocationLookup()
		{
			usAliasMap["ALABAMA"] = "AL";
			usAliasMap["ALASKA"] = "AK";
			usAliasMap["ARKANSAS"] = "AR";			
			usAliasMap["ARIZONA"] = "AZ";
			usAliasMap["CALIFORNIA"] = "CA";
			usAliasMap["COLORADO"] = "CO";
			usAliasMap["CONNECTICUT"] = "CT";
			usAliasMap["DELAWARE"] = "DE";
			usAliasMap["DISTRICT OF COLUMBIA"] = "DC";
			usAliasMap["FLORIDA"] = "FL";
			usAliasMap["GEORGIA"] = "GA";
			usAliasMap["HAWAII"] = "HI";
			usAliasMap["IDAHO"] = "ID";
			usAliasMap["ILLINOIS"] = "IL";
			usAliasMap["INDIANA"] = "IN";
			usAliasMap["IOWA"] = "IA";
			usAliasMap["KANSAS"] = "KS";
			usAliasMap["KENTUCKY"] = "KY";
			usAliasMap["LOUISIANA"] = "LA";
			usAliasMap["MAINE"] = "ME";
			usAliasMap["MARYLAND"] = "MD";
			usAliasMap["MASSACHUSETTS"] = "MA";                        
			usAliasMap["MICHIGAN"] = "MI";
			usAliasMap["MINNESOTA"] = "MN";
			usAliasMap["MISSISSIPPI"] = "MS";
			usAliasMap["MISSOURI"] = "MO";
			usAliasMap["MONTANA"] = "MT";
			usAliasMap["NEBRASKA"] = "NE";
			usAliasMap["NEVADA"] = "NV";
			usAliasMap["NEW HAMPSHIRE"] = "NH";
			usAliasMap["NEW JERSEY"] = "NJ";
			usAliasMap["NEW MEXICO"] = "NM";
			usAliasMap["NEW YORK"] = "NY";
			usAliasMap["NORTH CAROLINA"] = "NC";
			usAliasMap["NORTH DAKOTA"] = "ND";
			usAliasMap["OHIO"] = "OH";
			usAliasMap["OKLAHOMA"] = "OK";
			usAliasMap["OREGON"] = "OR";
			usAliasMap["PENNSYLVANIA"] = "PA";
			usAliasMap["RHODE ISLAND"] = "RI";
			usAliasMap["SOUTH CAROLINA"] = "SC";
			usAliasMap["SOUTH DAKOTA"] = "SD";
			usAliasMap["TENNESSEE"] = "TN";
			usAliasMap["TEXAS"] = "TX";
			usAliasMap["UTAH"] = "UT";
			usAliasMap["VERMONT"] = "VT";
			usAliasMap["VIRGINIA"] = "VA";
			usAliasMap["WASHINGTON"] = "WA";
			usAliasMap["WEST VIRGINIA"] = "WV";
			usAliasMap["WISCONSIN"] = "WI";
			usAliasMap["WYOMING"] = "WY";

            worldAliasMap["ARUBA"] = "ABW";
			worldAliasMap["AFGHANISTAN"] = "AFG";
			worldAliasMap["ANGOLA"] = "AGO";
			worldAliasMap["ANGUILLA"] = "AIA";
			worldAliasMap["ÅLAND ISLANDS"] = "ALA";
			worldAliasMap["ALAND ISLANDS"] = "ALA";
			worldAliasMap["ALBANIA"] = "ALB";
			worldAliasMap["ANDORRA"] = "AND";
			worldAliasMap["NETHERLANDS ANTILLES"] = "ANT";
			worldAliasMap["UNITED ARAB EMIRATES"] = "ARE";
			worldAliasMap["ARGENTINA"] = "ARG";
			worldAliasMap["ARMENIA"] = "ARM";
			worldAliasMap["AMERICAN SAMOA"] = "ASM";
			worldAliasMap["ANTARCTICA"] = "ATA";
			worldAliasMap["FRENCH SOUTHERN TERRITORIES"] = "ATF";
			worldAliasMap["ANTIGUA AND BARBUDA"] = "ATG";
			worldAliasMap["AUSTRALIA"] = "AUS";
			worldAliasMap["AUSTRIA"] = "AUT";
			worldAliasMap["AZERBAIJAN"] = "AZE";			
			worldAliasMap["BURUNDI"] = "BDI";
			worldAliasMap["BELGIUM"] = "BEL";
			worldAliasMap["BENIN"] = "BEN";
			worldAliasMap["BURKINA FASO"] = "BFA";
			worldAliasMap["BANGLADESH"] = "BGD";
			worldAliasMap["BULGARIA"] = "BGR";
			worldAliasMap["BAHRAIN"] = "BHR";
			worldAliasMap["BAHAMAS"] = "BHS";
			worldAliasMap["BOSNIA AND HERZEGOVINA"] = "BIH";
			worldAliasMap["SAINT BARTHELEMY"] = "BLM";
			worldAliasMap["SAINT BARTHÉLEMY"] = "BLM";
			worldAliasMap["BELARUS"] = "BLR";
			worldAliasMap["BELIZE"] = "BLZ";
			worldAliasMap["BERMUDA"] = "BMU";
			worldAliasMap["BOLIVIA"] = "BOL";
			worldAliasMap["BRAZIL"] = "BRA";
			worldAliasMap["BARBADOS"] = "BRB";
			worldAliasMap["BRUNEI DARUSSALAM"] = "BRN";
			worldAliasMap["BHUTAN"] = "BTN";
			worldAliasMap["BOUVET ISLAND"] = "BVT";
			worldAliasMap["BOTSWANA"] = "BWA";
			worldAliasMap["CENTRAL AFRICAN REPUBLIC"] = "CAF";
			worldAliasMap["CANADA"] = "CAN";
			worldAliasMap["COCOS (KEELING) ISLANDS"] = "CCK";
			worldAliasMap["SWITZERLAND"] = "CHE";
			worldAliasMap["CHILE"] = "CHL";
			worldAliasMap["CHINA"] = "CHN";
			worldAliasMap["COTE D'IVOIRE"] = "CIV";
			worldAliasMap["CÔTE D'IVOIRE"] ="CIV";
			worldAliasMap["CAMEROON"] = "CMR";
			worldAliasMap["CONGO, DEMOCRATIC REPUBLIC OF THE"] = "ZAR"; // ISO is COD but map appears not to support it
			worldAliasMap["DEMOCRATIC REPUBLIC OF THE CONGO"] = "ZAR";
			worldAliasMap["CONGO| DEMOCRATIC REPUBLIC OF THE"] = "ZAR";
			worldAliasMap["CONGO, REPUBLIC OF THE"] = "COG";
			worldAliasMap["CONGO| REPUBLIC OF THE"] = "COG";
			worldAliasMap["REPUBLIC OF THE CONGO"] = "COG"
			worldAliasMap["CONGO"] = "COG";
			worldAliasMap["COOK ISLANDS"] = "COK";
			worldAliasMap["COLOMBIA"] = "COL";
			worldAliasMap["COMOROS"] = "COM";
			worldAliasMap["CAPE VERDE"] = "CPV";
			worldAliasMap["COSTA RICA"] = "CRI";
			worldAliasMap["CUBA"] = "CUB";
			worldAliasMap["CHRISTMAS ISLAND"] = "CXR";
			worldAliasMap["CAYMAN ISLANDS"] = "CYM";
			worldAliasMap["CYPRUS"] = "CYP";
			worldAliasMap["CZECH REPUBLIC"] = "CZE";
			worldAliasMap["GERMANY"] = "DEU";
			worldAliasMap["DJIBOUTI"] = "DJI";
			worldAliasMap["DOMINICA"] = "DMA";
			worldAliasMap["DENMARK"] = "DNK";
			worldAliasMap["DOMINICAN REPUBLIC"] = "DOM";
			worldAliasMap["ALGERIA"] = "DZA";
			worldAliasMap["ECUADOR"] = "ECU";
			worldAliasMap["EGYPT"] = "EGY";
			worldAliasMap["ERITREA"] = "ERI";
			worldAliasMap["WESTERN SAHARA"] = "ESH";
			worldAliasMap["SPAIN"] = "ESP";
			worldAliasMap["ESTONIA"] = "EST";
			worldAliasMap["ETHIOPIA"] = "ETH";
			worldAliasMap["FINLAND"] = "FIN";
			worldAliasMap["FIJI"] = "FJI";
			worldAliasMap["FALKLAND ISLANDS (MALVINAS)"] = "FLK";
			worldAliasMap["FRANCE"] = "FRA";
			worldAliasMap["FAROE ISLANDS"] = "FRO";
			worldAliasMap["FEDERATED STATES OF MICRONESIA"] = "FSM";
			worldAliasMap["MICRONESIA, FEDERATED STATES OF"] = "FSM";
			worldAliasMap["GABON"] = "GAB";
			worldAliasMap["UNITED KINGDOM"] = "GBR";
			worldAliasMap["UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND"] = "GBR";
			worldAliasMap["GEORGIA"] = "GEO";
			worldAliasMap["GUERNSEY"] = "GGY";
			worldAliasMap["GHANA"] = "GHA";
			worldAliasMap["GIBRALTAR"] = "GIB";
			worldAliasMap["GUINEA"] = "GIN";
			worldAliasMap["GUADELOUPE"] = "GLP";
			worldAliasMap["GAMBIA"] = "GMB";
			worldAliasMap["GUINEA-BISSAU"] = "GNB";
			worldAliasMap["EQUATORIAL GUINEA"] = "GNQ";
			worldAliasMap["GREECE"] = "GRC";
			worldAliasMap["GRENADA"] = "GRD";
			worldAliasMap["GREENLAND"] = "GRL";
			worldAliasMap["GUATEMALA"] = "GTM";
			worldAliasMap["FRENCH GUIANA"] = "GUF";
			worldAliasMap["GUAM"] = "GUM";
			worldAliasMap["GUYANA"] = "GUY";
			worldAliasMap["HONG KONG"] = "HKG";
			worldAliasMap["HEARD ISLAND AND MCDONALD ISLANDS"] = "HMD";
			worldAliasMap["HONDURAS"] = "HND";
			worldAliasMap["CROATIA"] = "HRV";
			worldAliasMap["HAITI"] = "HTI";
			worldAliasMap["HUNGARY"] = "HUN";
			worldAliasMap["INDONESIA"] = "IDN";
			worldAliasMap["ISLE OF MAN"] = "IMN";
			worldAliasMap["INDIA"] = "IND";
			worldAliasMap["BRITISH INDIAN OCEAN TERRITORY"] = "IOT";
			worldAliasMap["IRELAND"] = "IRL";
			worldAliasMap["IRAN"] = "IRN";
			worldAliasMap["IRAN (ISLAMIC REPUBLIC OF)"] = "IRN";
			worldAliasMap["IRAN, ISLAMIC REPUBLIC OF"] = "IRN";
			worldAliasMap["IRAQ"] = "IRQ";
			worldAliasMap["ICELAND"] = "ISL";
			worldAliasMap["ISRAEL"] = "ISR";
			worldAliasMap["ITALY"] = "ITA";
			worldAliasMap["JAMAICA"] = "JAM";
			worldAliasMap["JERSEY"] = "JEY";
			worldAliasMap["JORDAN"] = "JOR";
			worldAliasMap["JAPAN"] = "JPN";
			worldAliasMap["KAZAKHSTAN"] = "KAZ";
			worldAliasMap["KENYA"] = "KEN";
			worldAliasMap["KYRGYZSTAN"] = "KGZ";
			worldAliasMap["CAMBODIA"] = "KHM";
			worldAliasMap["KIRIBATI"] = "KIR";
			worldAliasMap["SAINT KITTS AND NEVIS"] = "KNA";
			worldAliasMap["SOUTH KOREA"] = "KOR";
			worldAliasMap["KOREA| SOUTH"] = "KOR";
			worldAliasMap["KOREA, SOUTH"] = "KOR";
			worldAliasMap["REPUBLIC OF KOREA"] = "KOR";
			worldAliasMap["KOREA, REPUBLIC OF"] = "KOR";
			worldAliasMap["KUWAIT"] = "KWT";
			worldAliasMap["LAOS"] = "LAO";
			worldAliasMap["LAO PEOPLE'S DEMOCRATIC REPUBLIC"] = "LAO";
			worldAliasMap["LEBANON"] = "LBN";
			worldAliasMap["LIBERIA"] = "LBR";
			worldAliasMap["LIBYA"] = "LBY";
			worldAliasMap["LIBYAN ARAB JAMAHIRIYA"] = "LBY";
			worldAliasMap["SAINT LUCIA"] = "LCA";
			worldAliasMap["LIECHTENSTEIN"] = "LIE";
			worldAliasMap["SRI LANKA"] = "LKA";
			worldAliasMap["LESOTHO"] = "LSO";
			worldAliasMap["LITHUANIA"] = "LTU";
			worldAliasMap["LUXEMBOURG"] = "LUX";
			worldAliasMap["LATVIA"] = "LVA";
			worldAliasMap["MACAO"] ="MAC";
			worldAliasMap["SAINT MARTIN (FRENCH PART)"] = "MAF";
			worldAliasMap["SAINT MARTIN"] = "MAF";
			worldAliasMap["MOROCCO"] = "MAR";
			worldAliasMap["MONACO"] = "MCO";
			worldAliasMap["MOLDOVA"] = "MDA";
			worldAliasMap["REPUBLIC OF MOLDOVA"] = "MDA";
			worldAliasMap["MOLDOVA, REPUBLIC OF"] = "MDA";
			worldAliasMap["MADAGASCAR"] = "MDG";
			worldAliasMap["MALDIVES"] = "MDV";
			worldAliasMap["MEXICO"] = "MEX";
			worldAliasMap["MARSHALL ISLANDS"] = "MHL";
			worldAliasMap["MACEDONIA"] = "MKD";
			worldAliasMap["THE FORMER YUGOSLAV REPUBLIC OF MACEDONIA"] = "MKD";
			worldAliasMap["TFYR OF MACEDONIA"] = "MKD";
			worldAliasMap["MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF"]= "MKD";
			worldAliasMap["MALI"] = "MLI";
			worldAliasMap["MALTA"] = "MLT";
			worldAliasMap["MYANMAR"] = "MMR";
            worldAliasMap["BURMA"] = "MMR";
            worldAliasMap["MONTENEGRO"] = "MNE";
			worldAliasMap["MONGOLIA"] = "MNG";
			worldAliasMap["NORTHERN MARIANA ISLANDS"] = "MNP";
			worldAliasMap["MOZAMBIQUE"] = "MOZ";
			worldAliasMap["MAURITANIA"] = "MRT";
			worldAliasMap["MONTSERRAT"] = "MSR";
			worldAliasMap["MARTINIQUE"] = "MTQ";
			worldAliasMap["MAURITIUS"] = "MUS";
			worldAliasMap["MALAWI"] = "MWI";
			worldAliasMap["MALAYSIA"] = "MYS";
			worldAliasMap["MAYOTTE"] = "MYT";
			worldAliasMap["NAMIBIA"] = "NAM";
			worldAliasMap["NEW CALEDONIA"] = "NCL";
			worldAliasMap["NIGER"] = "NER";
			worldAliasMap["NORFOLK ISLAND"] = "NFK";
			worldAliasMap["NIGERIA"] = "NGA";
			worldAliasMap["NICARAGUA"] = "NIC";
			worldAliasMap["NIUE"] = "NIU";
			worldAliasMap["NETHERLANDS"] = "NLD";
			worldAliasMap["NORWAY"] = "NOR";
			worldAliasMap["NEPAL"] = "NPL";
			worldAliasMap["NAURU"] = "NRU";
			worldAliasMap["NEW ZEALAND"] = "NZL";
			worldAliasMap["OMAN"] = "OMN";
			worldAliasMap["PAKISTAN"] = "PAK";
			worldAliasMap["PANAMA"] = "PAN";
			worldAliasMap["PITCAIRN"] = "PCN";
			worldAliasMap["PITCAIRN ISLANDS"] = "PCN";
			worldAliasMap["PERU"] = "PER";
			worldAliasMap["PHILIPPINES"] = "PHL";
			worldAliasMap["PALAU"] = "PLW";
			worldAliasMap["PAPUA NEW GUINEA"] = "PNG";
			worldAliasMap["POLAND"] = "POL";
			worldAliasMap["PUERTO RICO"] = "PRI";
			worldAliasMap["NORTH KOREA"] = "PRK";
			worldAliasMap["KOREA| NORTH"] = "PRK";
			worldAliasMap["KOREA, NORTH"] = "PRK";
			worldAliasMap["DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA"] = "PRK";
			worldAliasMap["KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF"] = "PRK";
			worldAliasMap["PORTUGAL"] = "PRT";
			worldAliasMap["PARAGUAY"] = "PRY";
			worldAliasMap["PALESTINIANT TERRITORY, OCCUPIED"] = "PSE";
			worldAliasMap["PALESTINIAN TERRITORY"] = "PSE";
			worldAliasMap["FRENCH POLYNESIA"] = "PYF";
			worldAliasMap["QATAR"] = "QAT";
			worldAliasMap["RÉUNION"] = "REU";
			worldAliasMap["ROMANIA"] = "ROM";
			worldAliasMap["RUSSIA"] = "RUS";
			worldAliasMap["RUSSIAN FEDERATION"] = "RUS";
			worldAliasMap["RWANDA"] = "RWA";
			worldAliasMap["SAUDI ARABIA"] = "SAU";
			worldAliasMap["SUDAN"] = "SDN";
			worldAliasMap["SENEGAL"] = "SEN";
			worldAliasMap["SINGAPORE"] = "SGP";
			worldAliasMap["SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS"] = "SGS";
			worldAliasMap["SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA"] = "SHN";
			worldAliasMap["SVALBARD AND JAN MAYEN"] = "SJM";
			worldAliasMap["SOLOMON ISLANDS"] = "SLB";
			worldAliasMap["SIERRA LEONE"] = "SLE";
			worldAliasMap["EL SALVADOR"] = "SLV";
			worldAliasMap["SAN MARINO"] = "SMR";
			worldAliasMap["SOMALIA"] = "SOM";
			worldAliasMap["SAINT PIERRE AND MIQUELON"] = "SPM";
			worldAliasMap["SERBIA"] = "SRB";
			worldAliasMap["SERBIA"] = "YUG";
			worldAliasMap["SAO TOME AND PRINCIPE"] = "STP";
			worldAliasMap["SURINAME"] = "SUR";
			worldAliasMap["SLOVAKIA"] = "SVK";
			worldAliasMap["SLOVENIA"] = "SVN";
			worldAliasMap["SWEDEN"] = "SWE";
			worldAliasMap["SWAZILAND"] = "SWZ";
			worldAliasMap["SEYCHELLES"] = "SYC";
			worldAliasMap["SYRIAN ARAB REPUBLIC"] = "SYR";
			worldAliasMap["SYRIA"] = "SYR";
			worldAliasMap["TURKS AND CAICOS ISLANDS"] = "TCA";
			worldAliasMap["CHAD"] = "TCD";
			worldAliasMap["TOGO"] = "TGO";
			worldAliasMap["THAILAND"] = "THA";
			worldAliasMap["TAJIKISTAN"] = "TJK";
			worldAliasMap["TOKELAU"] = "TKL";
			worldAliasMap["TURKMENISTAN"] = "TKM";
			worldAliasMap["TIMOR-LESTE"] = "TLS";
			worldAliasMap["TONGA"] = "TON";
			worldAliasMap["TRINIDAD AND TOBAGO"] = "TTO";
			worldAliasMap["TUNISIA"] = "TUN";
			worldAliasMap["TURKEY"] = "TUR";
			worldAliasMap["TUVALU"] = "TUV";
			worldAliasMap["TAIWAN, PROVINCE OF CHINA"] = "TWN";
			worldAliasMap["TAIWAN"] = "TWN";
			worldAliasMap["TANZANIA"] = "TZA";
			worldAliasMap["UGANDA"] = "UGA";
			worldAliasMap["UKRAINE"] = "UKR";
			worldAliasMap["UNITED STATES MINOR OUTLYING ISLANDS"] = "UMI";
			worldAliasMap["URUGUAY"] = "URY";
			worldAliasMap["UNITED STATES"] = "USA";
			worldAliasMap["UNITED STATES OF AMERICA"] = "USA";
			worldAliasMap["UZBEKISTAN"] = "UZB";
			worldAliasMap["HOLY SEE (VATICAN CITY STATE)"] = "VAT";
			worldAliasMap["VATICAN CITY"] = "VAT";
			worldAliasMap["SAINT VINCENT AND THE GRENADINES"] = "VCT";
			worldAliasMap["VENEZUELA"] = "VEN";
			worldAliasMap["VIRGIN ISLANDS, BRITISH"] = "VGB";
			worldAliasMap["BRITISH VIRGIN ISLANDS"] = "VGB";
			worldAliasMap["VIRGIN ISLANDS, U.S."] = "VIR";
			worldAliasMap["UNITED STATES VIRGIN ISLANDS"] = "VIR";
			worldAliasMap["VIETNAM"] = "VNM";
			worldAliasMap["VIET NAM"] = "VNM";
			worldAliasMap["VANUATU"] = "VUT";
			worldAliasMap["WALLIS AND FUTUNA"] = "WLF";
			worldAliasMap["SAMOA"] = "WSM";
			worldAliasMap["YEMEN"] = "YEM";
			worldAliasMap["SOUTH AFRICA"] = "ZAF";
			worldAliasMap["ZAMBIA"] = "ZMB";
			worldAliasMap["ZIMBABWE"] = "ZWE";
		}
		
		public function getLocation(name:String, mapType:String):String {
			var aliasMap:Object = getAliasMap(mapType);
			var location:String = aliasMap[name.toUpperCase()];
            if (location == null) {
                return name;
            } else {
                return location;
            }
		}

        
		
		private function getAliasMap(mapType:String):Object {
			var aliasMap:Object;
			switch (mapType) {
				case "1":
					aliasMap = usAliasMap;
					break;
				default:
					aliasMap = worldAliasMap;
					break;				
			}
			return aliasMap;
		}

		public static function instance():MapLocationLookup {
			return new MapLocationLookup();
		}

        public function getAllLocations(param:String):Object {
            return getAliasMap(param);
        }}
}