
package com.easyinsight.rowutil.v2web;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BasicAuthEIV2APIService", targetNamespace = "http://v2.api.easyinsight.com/", wsdlLocation = "https://www.easy-insight.com/app/services/EIDataV2?wsdl")
public class BasicAuthEIV2APIService
    extends Service
{

    private final static URL BASICAUTHEIV2APISERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("https://www.easy-insight.com/app/services/EIDataV2?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        BASICAUTHEIV2APISERVICE_WSDL_LOCATION = url;
    }

    public BasicAuthEIV2APIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BasicAuthEIV2APIService() {
        super(BASICAUTHEIV2APISERVICE_WSDL_LOCATION, new QName("http://v2.api.easyinsight.com/", "BasicAuthEIV2APIService"));
    }

    /**
     * 
     * @return
     *     returns EIDataV2
     */
    @WebEndpoint(name = "BasicAuthEIV2APIPort")
    public EIDataV2 getBasicAuthEIV2APIPort() {
        return (EIDataV2)super.getPort(new QName("http://v2.api.easyinsight.com/", "BasicAuthEIV2APIPort"), EIDataV2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EIDataV2
     */
    @WebEndpoint(name = "BasicAuthEIV2APIPort")
    public EIDataV2 getBasicAuthEIV2APIPort(WebServiceFeature... features) {
        return (EIDataV2)super.getPort(new QName("http://v2.api.easyinsight.com/", "BasicAuthEIV2APIPort"), EIDataV2.class, features);
    }

}
