
package com.easyinsight.rowutil.v2web;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EIDataV2", targetNamespace = "http://v2.api.easyinsight.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EIDataV2 {


    /**
     * 
     * @param where
     * @param dataSourceName
     */
    @WebMethod
    @RequestWrapper(localName = "deleteRows", targetNamespace = "http://v2.api.easyinsight.com/", className = "com.easyinsight.rowutil.v2web.DeleteRows")
    @ResponseWrapper(localName = "deleteRowsResponse", targetNamespace = "http://v2.api.easyinsight.com/", className = "com.easyinsight.rowutil.v2web.DeleteRowsResponse")
    public void deleteRows(
        @WebParam(name = "dataSourceName", targetNamespace = "")
        String dataSourceName,
        @WebParam(name = "where", targetNamespace = "")
        Where where);

    /**
     * 
     * @param dataSourceName
     * @return
     *     returns com.easyinsight.rowutil.v2web.DataSourceInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSourceInfo", targetNamespace = "http://v2.api.easyinsight.com/", className = "com.easyinsight.rowutil.v2web.GetSourceInfo")
    @ResponseWrapper(localName = "getSourceInfoResponse", targetNamespace = "http://v2.api.easyinsight.com/", className = "com.easyinsight.rowutil.v2web.GetSourceInfoResponse")
    public DataSourceInfo getSourceInfo(
        @WebParam(name = "dataSourceName", targetNamespace = "")
        String dataSourceName);

    /**
     * 
     * @param changeDataSourceToMatch
     * @param where
     * @param dataSourceName
     * @param row
     */
    @WebMethod
    @RequestWrapper(localName = "updateRow", targetNamespace = "http://v2.api.easyinsight.com/", className = "com.easyinsight.rowutil.v2web.UpdateRow")
    @ResponseWrapper(localName = "updateRowResponse", targetNamespace = "http://v2.api.easyinsight.com/", className = "com.easyinsight.rowutil.v2web.UpdateRowResponse")
    public void updateRow(
        @WebParam(name = "dataSourceName", targetNamespace = "")
        String dataSourceName,
        @WebParam(name = "row", targetNamespace = "")
        Row row,
        @WebParam(name = "where", targetNamespace = "")
        Where where,
        @WebParam(name = "changeDataSourceToMatch", targetNamespace = "")
        boolean changeDataSourceToMatch);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateCredentials", targetNamespace = "http://v2.api.easyinsight.com/", className = "com.easyinsight.rowutil.v2web.ValidateCredentials")
    @ResponseWrapper(localName = "validateCredentialsResponse", targetNamespace = "http://v2.api.easyinsight.com/", className = "com.easyinsight.rowutil.v2web.ValidateCredentialsResponse")
    public boolean validateCredentials();

    /**
     * 
     * @param changeDataSourceToMatch
     * @param dataSourceName
     * @param row
     */
    @WebMethod
    @RequestWrapper(localName = "addRow", targetNamespace = "http://v2.api.easyinsight.com/", className = "com.easyinsight.rowutil.v2web.AddRow")
    @ResponseWrapper(localName = "addRowResponse", targetNamespace = "http://v2.api.easyinsight.com/", className = "com.easyinsight.rowutil.v2web.AddRowResponse")
    public void addRow(
        @WebParam(name = "dataSourceName", targetNamespace = "")
        String dataSourceName,
        @WebParam(name = "row", targetNamespace = "")
        Row row,
        @WebParam(name = "changeDataSourceToMatch", targetNamespace = "")
        boolean changeDataSourceToMatch);

    /**
     * 
     * @param changeDataSourceToMatch
     * @param where
     * @param dataSourceName
     * @param rows
     */
    @WebMethod
    @RequestWrapper(localName = "updateRows", targetNamespace = "http://v2.api.easyinsight.com/", className = "com.easyinsight.rowutil.v2web.UpdateRows")
    @ResponseWrapper(localName = "updateRowsResponse", targetNamespace = "http://v2.api.easyinsight.com/", className = "com.easyinsight.rowutil.v2web.UpdateRowsResponse")
    public void updateRows(
        @WebParam(name = "dataSourceName", targetNamespace = "")
        String dataSourceName,
        @WebParam(name = "rows", targetNamespace = "")
        List<Row> rows,
        @WebParam(name = "where", targetNamespace = "")
        Where where,
        @WebParam(name = "changeDataSourceToMatch", targetNamespace = "")
        boolean changeDataSourceToMatch);

    /**
     * 
     * @param changeDataSourceToMatch
     * @param dataSourceName
     * @param rows
     */
    @WebMethod
    @RequestWrapper(localName = "addRows", targetNamespace = "http://v2.api.easyinsight.com/", className = "com.easyinsight.rowutil.v2web.AddRows")
    @ResponseWrapper(localName = "addRowsResponse", targetNamespace = "http://v2.api.easyinsight.com/", className = "com.easyinsight.rowutil.v2web.AddRowsResponse")
    public void addRows(
        @WebParam(name = "dataSourceName", targetNamespace = "")
        String dataSourceName,
        @WebParam(name = "rows", targetNamespace = "")
        List<Row> rows,
        @WebParam(name = "changeDataSourceToMatch", targetNamespace = "")
        boolean changeDataSourceToMatch);

    /**
     * 
     * @param changeDataSourceToMatch
     * @param dataSourceName
     * @param rows
     */
    @WebMethod
    @RequestWrapper(localName = "replaceRows", targetNamespace = "http://v2.api.easyinsight.com/", className = "com.easyinsight.rowutil.v2web.ReplaceRows")
    @ResponseWrapper(localName = "replaceRowsResponse", targetNamespace = "http://v2.api.easyinsight.com/", className = "com.easyinsight.rowutil.v2web.ReplaceRowsResponse")
    public void replaceRows(
        @WebParam(name = "dataSourceName", targetNamespace = "")
        String dataSourceName,
        @WebParam(name = "rows", targetNamespace = "")
        List<Row> rows,
        @WebParam(name = "changeDataSourceToMatch", targetNamespace = "")
        boolean changeDataSourceToMatch);

}
