
package com.easyinsight.datafeeds.custom.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Sun Nov 08 23:40:11 MST 2009
 * Generated source version: 2.2.3
 * 
 */

public final class DataProvider_DataProviderPort_Client {

    private static final QName SERVICE_NAME = new QName("http://sampleimpl.easyinsight.com/", "DataProviderService");

    private DataProvider_DataProviderPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = DataProviderService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DataProviderService ss = new DataProviderService(wsdlURL, SERVICE_NAME);
        DataProvider port = ss.getDataProviderPort();  
        
        {
        System.out.println("Invoking getColumns...");
        java.util.List<java.lang.String> _getColumns__return = port.getColumns();
        System.out.println("getColumns.result=" + _getColumns__return);


        }
        {
        System.out.println("Invoking getPropertiesForDefinition...");
        java.util.List<com.easyinsight.datafeeds.custom.client.PropertyMetadata> _getPropertiesForDefinition__return = port.getPropertiesForDefinition();
        System.out.println("getPropertiesForDefinition.result=" + _getPropertiesForDefinition__return);


        }
        {
        System.out.println("Invoking getFields...");
        com.easyinsight.datafeeds.custom.client.Folder _getFields__return = port.getFields();
        System.out.println("getFields.result=" + _getFields__return);


        }
        {
        System.out.println("Invoking getPossibleStringValues...");
        java.lang.String _getPossibleStringValues_column = "";
        java.util.List<com.easyinsight.datafeeds.custom.client.Property> _getPossibleStringValues_properties = null;
        java.util.List<com.easyinsight.datafeeds.custom.client.StringValue> _getPossibleStringValues__return = port.getPossibleStringValues(_getPossibleStringValues_column, _getPossibleStringValues_properties);
        System.out.println("getPossibleStringValues.result=" + _getPossibleStringValues__return);


        }
        {
        System.out.println("Invoking defineDataSource...");
        java.util.List<com.easyinsight.datafeeds.custom.client.Property> _defineDataSource_properties = null;
        java.lang.String _defineDataSource__return = port.defineDataSource(_defineDataSource_properties);
        System.out.println("defineDataSource.result=" + _defineDataSource__return);


        }
        {
        System.out.println("Invoking getSpecifications...");
        java.util.List<com.easyinsight.datafeeds.custom.client.FilterSpecification> _getSpecifications__return = port.getSpecifications();
        System.out.println("getSpecifications.result=" + _getSpecifications__return);


        }
        {
        System.out.println("Invoking getRows...");
        java.util.List<java.lang.String> _getRows_columns = null;
        com.easyinsight.datafeeds.custom.client.Where _getRows_where = null;
        java.util.List<com.easyinsight.datafeeds.custom.client.Property> _getRows_properties = null;
        java.util.List<com.easyinsight.datafeeds.custom.client.Row> _getRows__return = port.getRows(_getRows_columns, _getRows_where, _getRows_properties);
        System.out.println("getRows.result=" + _getRows__return);


        }
        {
        System.out.println("Invoking getPossibleDateValues...");
        java.lang.String _getPossibleDateValues_column = "";
        java.util.List<com.easyinsight.datafeeds.custom.client.Property> _getPossibleDateValues_properties = null;
        java.util.List<com.easyinsight.datafeeds.custom.client.DateValue> _getPossibleDateValues__return = port.getPossibleDateValues(_getPossibleDateValues_column, _getPossibleDateValues_properties);
        System.out.println("getPossibleDateValues.result=" + _getPossibleDateValues__return);


        }

        System.exit(0);
    }

}
