package com.easyinsight.datafeeds.custom.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Sun Nov 08 23:40:11 MST 2009
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://sampleimpl.easyinsight.com/", name = "DataProvider")
@XmlSeeAlso({ObjectFactory.class})
public interface DataProvider {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getColumns", targetNamespace = "http://sampleimpl.easyinsight.com/", className = "com.easyinsight.datafeeds.custom.client.GetColumns")
    @ResponseWrapper(localName = "getColumnsResponse", targetNamespace = "http://sampleimpl.easyinsight.com/", className = "com.easyinsight.datafeeds.custom.client.GetColumnsResponse")
    @WebMethod
    public java.util.List<java.lang.String> getColumns();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPropertiesForDefinition", targetNamespace = "http://sampleimpl.easyinsight.com/", className = "com.easyinsight.datafeeds.custom.client.GetPropertiesForDefinition")
    @ResponseWrapper(localName = "getPropertiesForDefinitionResponse", targetNamespace = "http://sampleimpl.easyinsight.com/", className = "com.easyinsight.datafeeds.custom.client.GetPropertiesForDefinitionResponse")
    @WebMethod
    public java.util.List<com.easyinsight.datafeeds.custom.client.PropertyMetadata> getPropertiesForDefinition();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFields", targetNamespace = "http://sampleimpl.easyinsight.com/", className = "com.easyinsight.datafeeds.custom.client.GetFields")
    @ResponseWrapper(localName = "getFieldsResponse", targetNamespace = "http://sampleimpl.easyinsight.com/", className = "com.easyinsight.datafeeds.custom.client.GetFieldsResponse")
    @WebMethod
    public com.easyinsight.datafeeds.custom.client.Folder getFields();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPossibleStringValues", targetNamespace = "http://sampleimpl.easyinsight.com/", className = "com.easyinsight.datafeeds.custom.client.GetPossibleStringValues")
    @ResponseWrapper(localName = "getPossibleStringValuesResponse", targetNamespace = "http://sampleimpl.easyinsight.com/", className = "com.easyinsight.datafeeds.custom.client.GetPossibleStringValuesResponse")
    @WebMethod
    public java.util.List<com.easyinsight.datafeeds.custom.client.StringValue> getPossibleStringValues(
        @WebParam(name = "column", targetNamespace = "")
        java.lang.String column,
        @WebParam(name = "properties", targetNamespace = "")
        java.util.List<com.easyinsight.datafeeds.custom.client.Property> properties
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "defineDataSource", targetNamespace = "http://sampleimpl.easyinsight.com/", className = "com.easyinsight.datafeeds.custom.client.DefineDataSource")
    @ResponseWrapper(localName = "defineDataSourceResponse", targetNamespace = "http://sampleimpl.easyinsight.com/", className = "com.easyinsight.datafeeds.custom.client.DefineDataSourceResponse")
    @WebMethod
    public java.lang.String defineDataSource(
        @WebParam(name = "properties", targetNamespace = "")
        java.util.List<com.easyinsight.datafeeds.custom.client.Property> properties
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSpecifications", targetNamespace = "http://sampleimpl.easyinsight.com/", className = "com.easyinsight.datafeeds.custom.client.GetSpecifications")
    @ResponseWrapper(localName = "getSpecificationsResponse", targetNamespace = "http://sampleimpl.easyinsight.com/", className = "com.easyinsight.datafeeds.custom.client.GetSpecificationsResponse")
    @WebMethod
    public java.util.List<com.easyinsight.datafeeds.custom.client.FilterSpecification> getSpecifications();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRows", targetNamespace = "http://sampleimpl.easyinsight.com/", className = "com.easyinsight.datafeeds.custom.client.GetRows")
    @ResponseWrapper(localName = "getRowsResponse", targetNamespace = "http://sampleimpl.easyinsight.com/", className = "com.easyinsight.datafeeds.custom.client.GetRowsResponse")
    @WebMethod
    public java.util.List<com.easyinsight.datafeeds.custom.client.Row> getRows(
        @WebParam(name = "columns", targetNamespace = "")
        java.util.List<Field> columns,
        @WebParam(name = "where", targetNamespace = "")
        com.easyinsight.datafeeds.custom.client.Where where,
        @WebParam(name = "properties", targetNamespace = "")
        java.util.List<com.easyinsight.datafeeds.custom.client.Property> properties
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPossibleDateValues", targetNamespace = "http://sampleimpl.easyinsight.com/", className = "com.easyinsight.datafeeds.custom.client.GetPossibleDateValues")
    @ResponseWrapper(localName = "getPossibleDateValuesResponse", targetNamespace = "http://sampleimpl.easyinsight.com/", className = "com.easyinsight.datafeeds.custom.client.GetPossibleDateValuesResponse")
    @WebMethod
    public java.util.List<com.easyinsight.datafeeds.custom.client.DateValue> getPossibleDateValues(
        @WebParam(name = "column", targetNamespace = "")
        java.lang.String column,
        @WebParam(name = "properties", targetNamespace = "")
        java.util.List<com.easyinsight.datafeeds.custom.client.Property> properties
    );
}
