
package com.easyinsight.datafeeds.oracle.history;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExternalReportWSSService", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", wsdlLocation = "https://bcy.bi.ap1.oraclecloud.com/xmlpserver/services/ExternalReportWSSService?wsdl")
public class ExternalReportWSSService_Service
    extends Service
{

    private final static URL EXTERNALREPORTWSSSERVICE_WSDL_LOCATION;
    private final static WebServiceException EXTERNALREPORTWSSSERVICE_EXCEPTION;
    private final static QName EXTERNALREPORTWSSSERVICE_QNAME = new QName("http://xmlns.oracle.com/oxp/service/PublicReportService", "ExternalReportWSSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://bcy.bi.ap1.oraclecloud.com/xmlpserver/services/ExternalReportWSSService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXTERNALREPORTWSSSERVICE_WSDL_LOCATION = url;
        EXTERNALREPORTWSSSERVICE_EXCEPTION = e;
    }

    public ExternalReportWSSService_Service() {
        super(__getWsdlLocation(), EXTERNALREPORTWSSSERVICE_QNAME);
    }

    public ExternalReportWSSService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXTERNALREPORTWSSSERVICE_QNAME, features);
    }

    public ExternalReportWSSService_Service(URL wsdlLocation) {
        super(wsdlLocation, EXTERNALREPORTWSSSERVICE_QNAME);
    }

    public ExternalReportWSSService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXTERNALREPORTWSSSERVICE_QNAME, features);
    }

    public ExternalReportWSSService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExternalReportWSSService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExternalReportWSSService
     */
    @WebEndpoint(name = "ExternalReportWSSService")
    public ExternalReportWSSService getExternalReportWSSService() {
        return super.getPort(new QName("http://xmlns.oracle.com/oxp/service/PublicReportService", "ExternalReportWSSService"), ExternalReportWSSService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExternalReportWSSService
     */
    @WebEndpoint(name = "ExternalReportWSSService")
    public ExternalReportWSSService getExternalReportWSSService(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/oxp/service/PublicReportService", "ExternalReportWSSService"), ExternalReportWSSService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXTERNALREPORTWSSSERVICE_EXCEPTION!= null) {
            throw EXTERNALREPORTWSSSERVICE_EXCEPTION;
        }
        return EXTERNALREPORTWSSSERVICE_WSDL_LOCATION;
    }

}
