
package com.easyinsight.datafeeds.oracle.history;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExternalReportWSSService", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExternalReportWSSService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getSecurityModelReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "getSecurityModel", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.GetSecurityModel")
    @ResponseWrapper(localName = "getSecurityModelResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.GetSecurityModelResponse")
    public String getSecurityModel();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "getBIPHTTPSessionIntervalReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "getBIPHTTPSessionInterval", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.GetBIPHTTPSessionInterval")
    @ResponseWrapper(localName = "getBIPHTTPSessionIntervalResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.GetBIPHTTPSessionIntervalResponse")
    public int getBIPHTTPSessionInterval();

    /**
     * 
     * @param reportRequest
     * @param appParams
     * @return
     *     returns com.easyinsight.datafeeds.oracle.history.ReportResponse
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "runReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "runReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.RunReport")
    @ResponseWrapper(localName = "runReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.RunReportResponse")
    public ReportResponse runReport(
        @WebParam(name = "reportRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        ReportRequest reportRequest,
        @WebParam(name = "appParams", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String appParams)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param reportAbsolutePath
     * @return
     *     returns com.easyinsight.datafeeds.oracle.history.ReportDefinition
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "getReportDefinitionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "getReportDefinition", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.GetReportDefinition")
    @ResponseWrapper(localName = "getReportDefinitionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.GetReportDefinitionResponse")
    public ReportDefinition getReportDefinition(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsolutePath)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param reportAbsolutePath
     * @param templateID
     * @param locale
     * @return
     *     returns byte[]
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "getTemplateReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "getTemplate", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.GetTemplate")
    @ResponseWrapper(localName = "getTemplateResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.GetTemplateResponse")
    public byte[] getTemplate(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsolutePath,
        @WebParam(name = "templateID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String templateID,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String locale)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param reportAbsolutePath
     * @return
     *     returns byte[]
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "getReportSampleDataReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "getReportSampleData", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.GetReportSampleData")
    @ResponseWrapper(localName = "getReportSampleDataResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.GetReportSampleDataResponse")
    public byte[] getReportSampleData(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsolutePath)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param reportAbsolutePath
     * @param locale
     * @return
     *     returns byte[]
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "getXDOSchemaReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "getXDOSchema", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.GetXDOSchema")
    @ResponseWrapper(localName = "getXDOSchemaResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.GetXDOSchemaResponse")
    public byte[] getXDOSchema(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsolutePath,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String locale)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param reportRequest
     * @return
     *     returns com.easyinsight.datafeeds.oracle.history.ParamNameValues
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "getReportParametersReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "getReportParameters", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.GetReportParameters")
    @ResponseWrapper(localName = "getReportParametersResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.GetReportParametersResponse")
    public ParamNameValues getReportParameters(
        @WebParam(name = "reportRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        ReportRequest reportRequest)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param reportAbsolutePath
     * @param templateID
     * @return
     *     returns java.util.List<com.easyinsight.datafeeds.oracle.history.ParamNameValue>
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "getTemplateParametersReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "getTemplateParameters", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.GetTemplateParameters")
    @ResponseWrapper(localName = "getTemplateParametersResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.GetTemplateParametersResponse")
    public List<ParamNameValue> getTemplateParameters(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsolutePath,
        @WebParam(name = "templateID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String templateID)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param folderAbsolutePath
     * @return
     *     returns com.easyinsight.datafeeds.oracle.history.CatalogContents
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "getFolderContentsReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "getFolderContents", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.GetFolderContents")
    @ResponseWrapper(localName = "getFolderContentsResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.GetFolderContentsResponse")
    public CatalogContents getFolderContents(
        @WebParam(name = "folderAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String folderAbsolutePath)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.easyinsight.datafeeds.oracle.history.DeliveryServiceDefinition
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getDeliveryServiceDefinitionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "getDeliveryServiceDefinition", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.GetDeliveryServiceDefinition")
    @ResponseWrapper(localName = "getDeliveryServiceDefinitionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.GetDeliveryServiceDefinitionResponse")
    public DeliveryServiceDefinition getDeliveryServiceDefinition()
        throws AccessDeniedException_Exception
    ;

    /**
     * 
     * @param deliveryRequest
     * @return
     *     returns java.lang.String
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "deliveryServiceReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "deliveryService", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.DeliveryService")
    @ResponseWrapper(localName = "deliveryServiceResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.DeliveryServiceResponse")
    public String deliveryService(
        @WebParam(name = "deliveryRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        DeliveryRequest deliveryRequest)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "validateLoginReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "validateLogin", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.ValidateLogin")
    @ResponseWrapper(localName = "validateLoginResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.ValidateLoginResponse")
    public boolean validateLogin();

    /**
     * 
     * @param reportAbsolutePath
     * @return
     *     returns boolean
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "hasReportAccessReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "hasReportAccess", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.HasReportAccess")
    @ResponseWrapper(localName = "hasReportAccessResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.HasReportAccessResponse")
    public boolean hasReportAccess(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsolutePath)
        throws InvalidParametersException_Exception
    ;

    /**
     * 
     * @param reportAbsolutePath
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "isReportExistReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "isReportExist", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.IsReportExist")
    @ResponseWrapper(localName = "isReportExistResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.IsReportExistResponse")
    public boolean isReportExist(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsolutePath)
        throws AccessDeniedException_Exception
    ;

    /**
     * 
     * @param folderAbsolutePath
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "isFolderExistReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "isFolderExist", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.IsFolderExist")
    @ResponseWrapper(localName = "isFolderExistResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.IsFolderExistResponse")
    public boolean isFolderExist(
        @WebParam(name = "folderAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String folderAbsolutePath)
        throws AccessDeniedException_Exception
    ;

    /**
     * 
     * @param folderAbsolutePathURL
     * @param xliffData
     * @param updateFlag
     * @param reportName
     * @param templateData
     * @param templateFileName
     * @param xliffFileName
     * @return
     *     returns java.lang.String
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "createReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "createReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.CreateReport")
    @ResponseWrapper(localName = "createReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.CreateReportResponse")
    public String createReport(
        @WebParam(name = "reportName", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportName,
        @WebParam(name = "folderAbsolutePathURL", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String folderAbsolutePathURL,
        @WebParam(name = "templateFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String templateFileName,
        @WebParam(name = "templateData", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        byte[] templateData,
        @WebParam(name = "XLIFFFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String xliffFileName,
        @WebParam(name = "XLIFFData", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        byte[] xliffData,
        @WebParam(name = "updateFlag", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        boolean updateFlag)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param reportAbsPath
     * @param newReportDefn
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "updateReportDefinitionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "updateReportDefinition", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.UpdateReportDefinition")
    @ResponseWrapper(localName = "updateReportDefinitionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.UpdateReportDefinitionResponse")
    public boolean updateReportDefinition(
        @WebParam(name = "reportAbsPath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsPath,
        @WebParam(name = "newReportDefn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        ReportDefinition newReportDefn)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param folderAbsolutePath
     * @return
     *     returns java.lang.String
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "createReportFolderReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "createReportFolder", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.CreateReportFolder")
    @ResponseWrapper(localName = "createReportFolderResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.CreateReportFolderResponse")
    public String createReportFolder(
        @WebParam(name = "folderAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String folderAbsolutePath)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param templateType
     * @param reportAbsolutePath
     * @param templateName
     * @param templateData
     * @param locale
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "uploadTemplateForReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "uploadTemplateForReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.UploadTemplateForReport")
    @ResponseWrapper(localName = "uploadTemplateForReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.UploadTemplateForReportResponse")
    public boolean uploadTemplateForReport(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsolutePath,
        @WebParam(name = "templateName", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String templateName,
        @WebParam(name = "templateType", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String templateType,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String locale,
        @WebParam(name = "templateData", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        byte[] templateData)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param reportAbsolutePath
     * @param templateName
     * @param templateData
     * @param locale
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "updateTemplateForReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "updateTemplateForReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.UpdateTemplateForReport")
    @ResponseWrapper(localName = "updateTemplateForReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.UpdateTemplateForReportResponse")
    public boolean updateTemplateForReport(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsolutePath,
        @WebParam(name = "templateName", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String templateName,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String locale,
        @WebParam(name = "templateData", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        byte[] templateData)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param reportAbsolutePath
     * @param templateFileName
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "removeTemplateForReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "removeTemplateForReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.RemoveTemplateForReport")
    @ResponseWrapper(localName = "removeTemplateForReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.RemoveTemplateForReportResponse")
    public boolean removeTemplateForReport(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsolutePath,
        @WebParam(name = "templateFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String templateFileName)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param reportRawDataChunk
     * @param reportDataChunk
     * @param fileID
     * @return
     *     returns java.lang.String
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "uploadReportDataChunkReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "uploadReportDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.UploadReportDataChunk")
    @ResponseWrapper(localName = "uploadReportDataChunkResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.UploadReportDataChunkResponse")
    public String uploadReportDataChunk(
        @WebParam(name = "fileID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String fileID,
        @WebParam(name = "reportDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        byte[] reportDataChunk,
        @WebParam(name = "reportRawDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportRawDataChunk)
        throws OperationFailedException_Exception
    ;

    /**
     * 
     * @param beginIdx
     * @param size
     * @param fileID
     * @return
     *     returns com.easyinsight.datafeeds.oracle.history.ReportDataChunk
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "downloadReportDataChunkReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "downloadReportDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.DownloadReportDataChunk")
    @ResponseWrapper(localName = "downloadReportDataChunkResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.DownloadReportDataChunkResponse")
    public ReportDataChunk downloadReportDataChunk(
        @WebParam(name = "fileID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String fileID,
        @WebParam(name = "beginIdx", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        int beginIdx,
        @WebParam(name = "size", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        int size)
        throws OperationFailedException_Exception
    ;

    /**
     * 
     * @param reportObjectAbsolutePathURL
     * @param objectZippedData
     * @param objectType
     * @return
     *     returns java.lang.String
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "uploadReportObjectReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "uploadReportObject", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.UploadReportObject")
    @ResponseWrapper(localName = "uploadReportObjectResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.UploadReportObjectResponse")
    public String uploadReportObject(
        @WebParam(name = "reportObjectAbsolutePathURL", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportObjectAbsolutePathURL,
        @WebParam(name = "objectType", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String objectType,
        @WebParam(name = "objectZippedData", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        byte[] objectZippedData)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param reportAbsolutePath
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "deleteReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.DeleteReport")
    @ResponseWrapper(localName = "deleteReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.DeleteReportResponse")
    public boolean deleteReport(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsolutePath)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param folderAbsolutePath
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteFolderReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "deleteFolder", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.DeleteFolder")
    @ResponseWrapper(localName = "deleteFolderResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.DeleteFolderResponse")
    public boolean deleteFolder(
        @WebParam(name = "folderAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String folderAbsolutePath)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param reportAbsolutePath
     * @return
     *     returns byte[]
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "downloadReportObjectReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "downloadReportObject", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.DownloadReportObject")
    @ResponseWrapper(localName = "downloadReportObjectResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.DownloadReportObjectResponse")
    public byte[] downloadReportObject(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsolutePath)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param submitReportData
     * @param appParams
     * @return
     *     returns java.lang.String
     * @throws AccessDeniedException_Exception
     * @throws SchedulingException_Exception
     */
    @WebMethod
    @WebResult(name = "submitReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "submitReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.SubmitReport")
    @ResponseWrapper(localName = "submitReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.easyinsight.datafeeds.oracle.history.SubmitReportResponse")
    public String submitReport(
        @WebParam(name = "submitReportData", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        byte[] submitReportData,
        @WebParam(name = "appParams", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String appParams)
        throws AccessDeniedException_Exception, SchedulingException_Exception
    ;

}
