drop table report_multi_color_property;
create table report_multi_color_property (
  report_multi_color_property_id bigint(20) auto_increment not null,
  report_property_id bigint(20) not null,
  color1Start integer not null default 0,
  color1StartEnabled tinyint(4) not null default 0,
  color1End integer not null default 0,
  color1EndEnabled tinyint(4) not null default 0,
  color2Start integer not null default 0,
  color2StartEnabled tinyint(4) not null default 0,
  color2End integer not null default 0,
  color2EndEnabled tinyint(4) not null default 0,
  color3Start integer not null default 0,
  color3StartEnabled tinyint(4) not null default 0,
  color3End integer not null default 0,
  color3EndEnabled tinyint(4) not null default 0,
  color4Start integer not null default 0,
  color4StartEnabled tinyint(4) not null default 0,
  color4End integer not null default 0,
  color4EndEnabled tinyint(4) not null default 0,
  color5Start integer not null default 0,
  color5StartEnabled tinyint(4) not null default 0,
  color5End integer not null default 0,
  color5EndEnabled tinyint(4) not null default 0,
  color6Start integer not null default 0,
  color6StartEnabled tinyint(4) not null default 0,
  color6End integer not null default 0,
  color6EndEnabled tinyint(4) not null default 0,
  color7Start integer not null default 0,
  color7StartEnabled tinyint(4) not null default 0,
  color7End integer not null default 0,
  color7EndEnabled tinyint(4) not null default 0,
  color8Start integer not null default 0,
  color8StartEnabled tinyint(4) not null default 0,
  color8End integer not null default 0,
  color8EndEnabled tinyint(4) not null default 0,
  color9Start integer not null default 0,
  color9StartEnabled tinyint(4) not null default 0,
  color9End integer not null default 0,
  color9EndEnabled tinyint(4) not null default 0,
  color10Start integer not null default 0,
  color10StartEnabled tinyint(4) not null default 0,
  color10End integer not null default 0,
  color10EndEnabled tinyint(4) not null default 0,
  color11Start integer not null default 0,
  color11StartEnabled tinyint(4) not null default 0,
  color11End integer not null default 0,
  color11EndEnabled tinyint(4) not null default 0,
  color12Start integer not null default 0,
  color12StartEnabled tinyint(4) not null default 0,
  color12End integer not null default 0,
  color12EndEnabled tinyint(4) not null default 0,
  color13Start integer not null default 0,
  color13StartEnabled tinyint(4) not null default 0,
  color13End integer not null default 0,
  color13EndEnabled tinyint(4) not null default 0,
  color14Start integer not null default 0,
  color14StartEnabled tinyint(4) not null default 0,
  color14End integer not null default 0,
  color14EndEnabled tinyint(4) not null default 0,
  color15Start integer not null default 0,
  color15StartEnabled tinyint(4) not null default 0,
  color15End integer not null default 0,
  color15EndEnabled tinyint(4) not null default 0,
  primary key (report_multi_color_property_id),
  constraint report_multi_color_property_ibfk1 foreign key (report_property_id) references report_property (report_property_id) on delete cascade
);