drop table if exists SURVEY_GIZMO;
create table SURVEY_GIZMO (TOKEN_KEY VARCHAR(255), SECRET_KEY VARCHAR(255), DATA_SOURCE_ID BIGINT(20));

drop table if exists SURVEYGIZMO_FORM_SOURCE;
create table SURVEYGIZMO_FORM_SOURCE (FORM_ID VARCHAR(255), DATA_SOURCE_ID BIGINT(20));