
package com.easyinsight.datafeeds.oracle.client;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OpportunityService", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OpportunityService {


    /**
     * 
     * @param optyId
     * @return
     *     returns com.easyinsight.datafeeds.oracle.client.Opportunity
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getOpportunity")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "getOpportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.GetOpportunity")
    @ResponseWrapper(localName = "getOpportunityResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.GetOpportunityResponse")
    public Opportunity getOpportunity(
        @WebParam(name = "optyId", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        long optyId)
        throws ServiceException
    ;

    /**
     * 
     * @param opportunity
     * @return
     *     returns com.easyinsight.datafeeds.oracle.client.Opportunity
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/createOpportunity")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "createOpportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.CreateOpportunity")
    @ResponseWrapper(localName = "createOpportunityResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.CreateOpportunityResponse")
    public Opportunity createOpportunity(
        @WebParam(name = "opportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        Opportunity opportunity)
        throws ServiceException
    ;

    /**
     * 
     * @param opportunity
     * @return
     *     returns com.easyinsight.datafeeds.oracle.client.Opportunity
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/updateOpportunity")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "updateOpportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.UpdateOpportunity")
    @ResponseWrapper(localName = "updateOpportunityResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.UpdateOpportunityResponse")
    public Opportunity updateOpportunity(
        @WebParam(name = "opportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        Opportunity opportunity)
        throws ServiceException
    ;

    /**
     * 
     * @param opportunity
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunity")
    @RequestWrapper(localName = "deleteOpportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DeleteOpportunity")
    @ResponseWrapper(localName = "deleteOpportunityResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DeleteOpportunityResponse")
    public void deleteOpportunity(
        @WebParam(name = "opportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        Opportunity opportunity)
        throws ServiceException
    ;

    /**
     * 
     * @param opportunity
     * @return
     *     returns com.easyinsight.datafeeds.oracle.client.Opportunity
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/mergeOpportunity")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "mergeOpportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.MergeOpportunity")
    @ResponseWrapper(localName = "mergeOpportunityResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.MergeOpportunityResponse")
    public Opportunity mergeOpportunity(
        @WebParam(name = "opportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        Opportunity opportunity)
        throws ServiceException
    ;

    /**
     * 
     * @param processControl
     * @param opportunity
     * @param changeOperation
     * @return
     *     returns java.util.List<com.easyinsight.datafeeds.oracle.client.Opportunity>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/processOpportunity")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "processOpportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.ProcessOpportunity")
    @ResponseWrapper(localName = "processOpportunityResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.ProcessOpportunityResponse")
    public List<Opportunity> processOpportunity(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        String changeOperation,
        @WebParam(name = "opportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        List<Opportunity> opportunity,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        ProcessControl processControl)
        throws ServiceException
    ;

    /**
     * 
     * @param processControl
     * @param processData
     * @return
     *     returns com.easyinsight.datafeeds.oracle.client.ProcessData
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/processCSOpportunity")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "processCSOpportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.ProcessCSOpportunity")
    @ResponseWrapper(localName = "processCSOpportunityResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.ProcessCSOpportunityResponse")
    public ProcessData processCSOpportunity(
        @WebParam(name = "processData", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        ProcessData processData,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        ProcessControl processControl)
        throws ServiceException
    ;

    /**
     * 
     * @param processControl
     * @param processData
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/processCSOpportunityAsync")
    @Oneway
    @RequestWrapper(localName = "processCSOpportunityAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.ProcessCSOpportunityAsync")
    public void processCSOpportunityAsync(
        @WebParam(name = "processData", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        ProcessData processData,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        ProcessControl processControl);

    /**
     * 
     * @param processControl
     * @param opportunity
     * @param changeOperation
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/processOpportunityAsync")
    @Oneway
    @RequestWrapper(localName = "processOpportunityAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.ProcessOpportunityAsync")
    public void processOpportunityAsync(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        String changeOperation,
        @WebParam(name = "opportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        List<Opportunity> opportunity,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        ProcessControl processControl);

    /**
     * 
     * @param opportunity
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityAsync")
    @Oneway
    @RequestWrapper(localName = "deleteOpportunityAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DeleteOpportunityAsync")
    public void deleteOpportunityAsync(
        @WebParam(name = "opportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        Opportunity opportunity);

    /**
     * 
     * @param optyId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getOpportunityAsync")
    @Oneway
    @RequestWrapper(localName = "getOpportunityAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.GetOpportunityAsync")
    public void getOpportunityAsync(
        @WebParam(name = "optyId", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        long optyId);

    /**
     * 
     * @param opportunity
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/createOpportunityAsync")
    @Oneway
    @RequestWrapper(localName = "createOpportunityAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.CreateOpportunityAsync")
    public void createOpportunityAsync(
        @WebParam(name = "opportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        Opportunity opportunity);

    /**
     * 
     * @param opportunity
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/mergeOpportunityAsync")
    @Oneway
    @RequestWrapper(localName = "mergeOpportunityAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.MergeOpportunityAsync")
    public void mergeOpportunityAsync(
        @WebParam(name = "opportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        Opportunity opportunity);

    /**
     * 
     * @param opportunity
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/updateOpportunityAsync")
    @Oneway
    @RequestWrapper(localName = "updateOpportunityAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.UpdateOpportunityAsync")
    public void updateOpportunityAsync(
        @WebParam(name = "opportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        Opportunity opportunity);

    /**
     * 
     * @param opportunityCompetitorVO
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityCompetitor")
    @RequestWrapper(localName = "deleteOpportunityCompetitor", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DeleteOpportunityCompetitor")
    @ResponseWrapper(localName = "deleteOpportunityCompetitorResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DeleteOpportunityCompetitorResponse")
    public void deleteOpportunityCompetitor(
        @WebParam(name = "opportunityCompetitorVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        OpportunityCompetitor opportunityCompetitorVO)
        throws ServiceException
    ;

    /**
     * 
     * @param opportunityLeadVO
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityLead")
    @RequestWrapper(localName = "deleteOpportunityLead", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DeleteOpportunityLead")
    @ResponseWrapper(localName = "deleteOpportunityLeadResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DeleteOpportunityLeadResponse")
    public void deleteOpportunityLead(
        @WebParam(name = "opportunityLeadVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        OpportunityLead opportunityLeadVO)
        throws ServiceException
    ;

    /**
     * 
     * @param opportunityReferenceVO
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityReference")
    @RequestWrapper(localName = "deleteOpportunityReference", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DeleteOpportunityReference")
    @ResponseWrapper(localName = "deleteOpportunityReferenceResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DeleteOpportunityReferenceResponse")
    public void deleteOpportunityReference(
        @WebParam(name = "opportunityReferenceVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        OpportunityReference opportunityReferenceVO)
        throws ServiceException
    ;

    /**
     * 
     * @param opportunityResourceVO
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityResource")
    @RequestWrapper(localName = "deleteOpportunityResource", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DeleteOpportunityResource")
    @ResponseWrapper(localName = "deleteOpportunityResourceResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DeleteOpportunityResourceResponse")
    public void deleteOpportunityResource(
        @WebParam(name = "opportunityResourceVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        OpportunityResource opportunityResourceVO)
        throws ServiceException
    ;

    /**
     * 
     * @param opportunityResponseVO
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityMktResponse")
    @RequestWrapper(localName = "deleteOpportunityMktResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DeleteOpportunityMktResponse")
    @ResponseWrapper(localName = "deleteOpportunityMktResponseResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DeleteOpportunityMktResponseResponse")
    public void deleteOpportunityMktResponse(
        @WebParam(name = "opportunityResponseVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        OpportunityResponse opportunityResponseVO)
        throws ServiceException
    ;

    /**
     * 
     * @param opportunityRevenueVO
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityRevenue")
    @RequestWrapper(localName = "deleteOpportunityRevenue", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DeleteOpportunityRevenue")
    @ResponseWrapper(localName = "deleteOpportunityRevenueResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DeleteOpportunityRevenueResponse")
    public void deleteOpportunityRevenue(
        @WebParam(name = "opportunityRevenueVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        Revenue opportunityRevenueVO)
        throws ServiceException
    ;

    /**
     * 
     * @param opportunitySourceVO
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunitySource")
    @RequestWrapper(localName = "deleteOpportunitySource", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DeleteOpportunitySource")
    @ResponseWrapper(localName = "deleteOpportunitySourceResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DeleteOpportunitySourceResponse")
    public void deleteOpportunitySource(
        @WebParam(name = "opportunitySourceVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        OpportunitySource opportunitySourceVO)
        throws ServiceException
    ;

    /**
     * 
     * @param opportunityCompetitorVO
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityCompetitorAsync")
    @Oneway
    @RequestWrapper(localName = "deleteOpportunityCompetitorAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DeleteOpportunityCompetitorAsync")
    public void deleteOpportunityCompetitorAsync(
        @WebParam(name = "opportunityCompetitorVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        OpportunityCompetitor opportunityCompetitorVO);

    /**
     * 
     * @param opportunityResponseVO
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityMktResponseAsync")
    @Oneway
    @RequestWrapper(localName = "deleteOpportunityMktResponseAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DeleteOpportunityMktResponseAsync")
    public void deleteOpportunityMktResponseAsync(
        @WebParam(name = "opportunityResponseVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        OpportunityResponse opportunityResponseVO);

    /**
     * 
     * @param opportunityRevenueVO
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityRevenueAsync")
    @Oneway
    @RequestWrapper(localName = "deleteOpportunityRevenueAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DeleteOpportunityRevenueAsync")
    public void deleteOpportunityRevenueAsync(
        @WebParam(name = "opportunityRevenueVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        Revenue opportunityRevenueVO);

    /**
     * 
     * @param opportunityResourceVO
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityResourceAsync")
    @Oneway
    @RequestWrapper(localName = "deleteOpportunityResourceAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DeleteOpportunityResourceAsync")
    public void deleteOpportunityResourceAsync(
        @WebParam(name = "opportunityResourceVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        OpportunityResource opportunityResourceVO);

    /**
     * 
     * @param opportunityLeadVO
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityLeadAsync")
    @Oneway
    @RequestWrapper(localName = "deleteOpportunityLeadAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DeleteOpportunityLeadAsync")
    public void deleteOpportunityLeadAsync(
        @WebParam(name = "opportunityLeadVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        OpportunityLead opportunityLeadVO);

    /**
     * 
     * @param opportunitySourceVO
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunitySourceAsync")
    @Oneway
    @RequestWrapper(localName = "deleteOpportunitySourceAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DeleteOpportunitySourceAsync")
    public void deleteOpportunitySourceAsync(
        @WebParam(name = "opportunitySourceVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        OpportunitySource opportunitySourceVO);

    /**
     * 
     * @param opportunityReferenceVO
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityReferenceAsync")
    @Oneway
    @RequestWrapper(localName = "deleteOpportunityReferenceAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DeleteOpportunityReferenceAsync")
    public void deleteOpportunityReferenceAsync(
        @WebParam(name = "opportunityReferenceVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        OpportunityReference opportunityReferenceVO);

    /**
     * 
     * @param optyId
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/doAutoAssignmentAsynchronously")
    @RequestWrapper(localName = "doAutoAssignmentAsynchronously", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DoAutoAssignmentAsynchronously")
    @ResponseWrapper(localName = "doAutoAssignmentAsynchronouslyResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DoAutoAssignmentAsynchronouslyResponse")
    public void doAutoAssignmentAsynchronously(
        @WebParam(name = "optyId", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        String optyId)
        throws ServiceException
    ;

    /**
     * 
     * @param optyId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/doAutoAssignmentAsynchronouslyAsync")
    @Oneway
    @RequestWrapper(localName = "doAutoAssignmentAsynchronouslyAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DoAutoAssignmentAsynchronouslyAsync")
    public void doAutoAssignmentAsynchronouslyAsync(
        @WebParam(name = "optyId", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        String optyId);

    /**
     * 
     * @param opportunityContactVO
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityContact")
    @RequestWrapper(localName = "deleteOpportunityContact", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DeleteOpportunityContact")
    @ResponseWrapper(localName = "deleteOpportunityContactResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DeleteOpportunityContactResponse")
    public void deleteOpportunityContact(
        @WebParam(name = "opportunityContactVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        OpportunityContact opportunityContactVO)
        throws ServiceException
    ;

    /**
     * 
     * @param opportunityContactVO
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityContactAsync")
    @Oneway
    @RequestWrapper(localName = "deleteOpportunityContactAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.DeleteOpportunityContactAsync")
    public void deleteOpportunityContactAsync(
        @WebParam(name = "opportunityContactVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        OpportunityContact opportunityContactVO);

    /**
     * 
     * @param findControl
     * @param findCriteria
     * @return
     *     returns java.util.List<com.easyinsight.datafeeds.oracle.client.Opportunity>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/findOpportunity")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "findOpportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.FindOpportunity")
    @ResponseWrapper(localName = "findOpportunityResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.FindOpportunityResponse")
    public List<Opportunity> findOpportunity(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        FindControl findControl)
        throws ServiceException
    ;

    /**
     * 
     * @param findControl
     * @param findCriteria
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/findOpportunityAsync")
    @Oneway
    @RequestWrapper(localName = "findOpportunityAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.FindOpportunityAsync")
    public void findOpportunityAsync(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        FindControl findControl);

    /**
     * 
     * @param salesAccountId
     * @return
     *     returns boolean
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/isSalesAccountUsedInOpportunity")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "isSalesAccountUsedInOpportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.IsSalesAccountUsedInOpportunity")
    @ResponseWrapper(localName = "isSalesAccountUsedInOpportunityResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.IsSalesAccountUsedInOpportunityResponse")
    public boolean isSalesAccountUsedInOpportunity(
        @WebParam(name = "salesAccountId", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        long salesAccountId)
        throws ServiceException
    ;

    /**
     * 
     * @param salesAccountId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/isSalesAccountUsedInOpportunityAsync")
    @Oneway
    @RequestWrapper(localName = "isSalesAccountUsedInOpportunityAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.IsSalesAccountUsedInOpportunityAsync")
    public void isSalesAccountUsedInOpportunityAsync(
        @WebParam(name = "salesAccountId", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        long salesAccountId);

    /**
     * 
     * @param deleteEntities
     * @return
     *     returns java.util.List<com.easyinsight.datafeeds.oracle.client.DeleteEntity>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/checkConstraint")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "checkConstraint", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.CheckConstraint")
    @ResponseWrapper(localName = "checkConstraintResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.CheckConstraintResponse")
    public List<DeleteEntity> checkConstraint(
        @WebParam(name = "deleteEntities", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        List<DeleteEntity> deleteEntities)
        throws ServiceException
    ;

    /**
     * 
     * @param deleteEntities
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/checkConstraintAsync")
    @Oneway
    @RequestWrapper(localName = "checkConstraintAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.CheckConstraintAsync")
    public void checkConstraintAsync(
        @WebParam(name = "deleteEntities", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        List<DeleteEntity> deleteEntities);

    /**
     * 
     * @param viewName
     * @param localeName
     * @return
     *     returns com.easyinsight.datafeeds.oracle.client.ObjAttrHints
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getDfltObjAttrHints")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "getDfltObjAttrHints", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.GetDfltObjAttrHints")
    @ResponseWrapper(localName = "getDfltObjAttrHintsResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.GetDfltObjAttrHintsResponse")
    public ObjAttrHints getDfltObjAttrHints(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        String localeName)
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getServiceLastUpdateTime")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "getServiceLastUpdateTime", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.GetServiceLastUpdateTime")
    @ResponseWrapper(localName = "getServiceLastUpdateTimeResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.GetServiceLastUpdateTimeResponse")
    public XMLGregorianCalendar getServiceLastUpdateTime()
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.easyinsight.datafeeds.oracle.client.ServiceViewInfo>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getEntityList")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "getEntityList", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.GetEntityList")
    @ResponseWrapper(localName = "getEntityListResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.GetEntityListResponse")
    public List<ServiceViewInfo> getEntityList()
        throws ServiceException
    ;

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getEntityListAsync")
    @Oneway
    @RequestWrapper(localName = "getEntityListAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.GetEntityListAsync")
    public void getEntityListAsync();

    /**
     * 
     * @param viewName
     * @param localeName
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getDfltObjAttrHintsAsync")
    @Oneway
    @RequestWrapper(localName = "getDfltObjAttrHintsAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.GetDfltObjAttrHintsAsync")
    public void getDfltObjAttrHintsAsync(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        String localeName);

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getServiceLastUpdateTimeAsync")
    @Oneway
    @RequestWrapper(localName = "getServiceLastUpdateTimeAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.easyinsight.datafeeds.oracle.client.GetServiceLastUpdateTimeAsync")
    public void getServiceLastUpdateTimeAsync();

}
