
package com.easyinsight.datafeeds.netsuite.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "NetSuiteService", targetNamespace = "urn:platform_2014_1.webservices.netsuite.com", wsdlLocation = "file:///Users/jamesboe/Downloads/WSDL_v2014_1_0/netsuite.wsdl")
public class NetSuiteService
    extends Service
{

    private final static URL NETSUITESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.easyinsight.datafeeds.netsuite.client.NetSuiteService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.easyinsight.datafeeds.netsuite.client.NetSuiteService.class.getResource(".");
            url = new URL(baseUrl, "file:///Users/jamesboe/Downloads/WSDL_v2014_1_0/netsuite.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:///Users/jamesboe/Downloads/WSDL_v2014_1_0/netsuite.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        NETSUITESERVICE_WSDL_LOCATION = url;
    }

    public NetSuiteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NetSuiteService(URL wsdlLocation) {
        super(wsdlLocation, new QName("urn:platform_2014_1.webservices.netsuite.com", "NetSuiteService"));
    }

    public NetSuiteService() {
        super(NETSUITESERVICE_WSDL_LOCATION, new QName("urn:platform_2014_1.webservices.netsuite.com", "NetSuiteService"));
    }

    /**
     * 
     * @return
     *     returns NetSuitePortType
     */
    @WebEndpoint(name = "NetSuitePort")
    public NetSuitePortType getNetSuitePort() {
        return super.getPort(new QName("urn:platform_2014_1.webservices.netsuite.com", "NetSuitePort"), NetSuitePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NetSuitePortType
     */
    @WebEndpoint(name = "NetSuitePort")
    public NetSuitePortType getNetSuitePort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:platform_2014_1.webservices.netsuite.com", "NetSuitePort"), NetSuitePortType.class, features);
    }

}
