
package com.easyinsight.datafeeds.netsuite.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SearchRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchRecord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchRecord", namespace = "urn:core_2014_1.platform.webservices.netsuite.com")
@XmlSeeAlso({
    SearchRecordBasic.class,
    PhoneCallSearch.class,
    ProjectTaskSearch.class,
    CalendarEventSearch.class,
    ResourceAllocationSearch.class,
    TaskSearch.class,
    PhoneCallSearchAdvanced.class,
    TaskSearchAdvanced.class,
    ProjectTaskSearchAdvanced.class,
    ResourceAllocationSearchAdvanced.class,
    CalendarEventSearchAdvanced.class,
    MessageSearch.class,
    NoteSearch.class,
    MessageSearchAdvanced.class,
    NoteSearchAdvanced.class,
    FileSearch.class,
    FolderSearch.class,
    FileSearchAdvanced.class,
    FolderSearchAdvanced.class,
    VendorSearch.class,
    JobStatusSearch.class,
    CustomerStatusSearch.class,
    OriginatingLeadSearch.class,
    CustomerSearch.class,
    PartnerSearch.class,
    JobSearch.class,
    EntityGroupSearch.class,
    ContactSearch.class,
    JobTypeSearch.class,
    JobStatusSearchAdvanced.class,
    ContactSearchAdvanced.class,
    VendorSearchAdvanced.class,
    CustomerStatusSearchAdvanced.class,
    JobSearchAdvanced.class,
    JobTypeSearchAdvanced.class,
    PartnerSearchAdvanced.class,
    CustomerSearchAdvanced.class,
    EntityGroupSearchAdvanced.class,
    TopicSearch.class,
    SolutionSearch.class,
    SupportCaseSearch.class,
    IssueSearch.class,
    TopicSearchAdvanced.class,
    SolutionSearchAdvanced.class,
    SupportCaseSearchAdvanced.class,
    IssueSearchAdvanced.class,
    BinSearch.class,
    PaymentMethodSearch.class,
    NoteTypeSearch.class,
    AccountingPeriodSearch.class,
    PriceLevelSearch.class,
    ItemRevisionSearch.class,
    ItemSearch.class,
    AccountSearch.class,
    RevRecScheduleSearch.class,
    InventoryNumberSearch.class,
    ClassificationSearch.class,
    WinLossReasonSearch.class,
    BillingScheduleSearch.class,
    PricingGroupSearch.class,
    LocationSearch.class,
    GiftCertificateSearch.class,
    CustomerMessageSearch.class,
    DepartmentSearch.class,
    ContactCategorySearch.class,
    NexusSearch.class,
    VendorCategorySearch.class,
    SubsidiarySearch.class,
    OtherNameCategorySearch.class,
    CurrencyRateSearch.class,
    CustomerCategorySearch.class,
    ContactRoleSearch.class,
    RevRecTemplateSearch.class,
    ItemAccountMappingSearch.class,
    UnitsTypeSearch.class,
    ExpenseCategorySearch.class,
    SalesRoleSearch.class,
    TermSearch.class,
    GlobalAccountMappingSearch.class,
    PartnerCategorySearch.class,
    ItemAccountMappingSearchAdvanced.class,
    NexusSearchAdvanced.class,
    ContactCategorySearchAdvanced.class,
    GiftCertificateSearchAdvanced.class,
    ClassificationSearchAdvanced.class,
    GlobalAccountMappingSearchAdvanced.class,
    AccountingPeriodSearchAdvanced.class,
    DepartmentSearchAdvanced.class,
    VendorCategorySearchAdvanced.class,
    PricingGroupSearchAdvanced.class,
    RevRecScheduleSearchAdvanced.class,
    ItemSearchAdvanced.class,
    PaymentMethodSearchAdvanced.class,
    PartnerCategorySearchAdvanced.class,
    ContactRoleSearchAdvanced.class,
    UnitsTypeSearchAdvanced.class,
    CurrencyRateSearchAdvanced.class,
    BillingScheduleSearchAdvanced.class,
    WinLossReasonSearchAdvanced.class,
    ItemRevisionSearchAdvanced.class,
    OtherNameCategorySearchAdvanced.class,
    InventoryNumberSearchAdvanced.class,
    LocationSearchAdvanced.class,
    CustomerMessageSearchAdvanced.class,
    RevRecTemplateSearchAdvanced.class,
    NoteTypeSearchAdvanced.class,
    PriceLevelSearchAdvanced.class,
    TermSearchAdvanced.class,
    CustomerCategorySearchAdvanced.class,
    ExpenseCategorySearchAdvanced.class,
    AccountSearchAdvanced.class,
    BinSearchAdvanced.class,
    SubsidiarySearchAdvanced.class,
    SalesRoleSearchAdvanced.class,
    TransactionSearch.class,
    OpportunitySearch.class,
    TransactionSearchAdvanced.class,
    OpportunitySearchAdvanced.class,
    ChargeSearch.class,
    ChargeSearchAdvanced.class,
    BudgetSearch.class,
    BudgetSearchAdvanced.class,
    AppPackageSearch.class,
    AppDefinitionSearch.class,
    CustomRecordSearch.class,
    CustomListSearch.class,
    AppDefinitionSearchAdvanced.class,
    CustomRecordSearchAdvanced.class,
    CustomListSearchAdvanced.class,
    AppPackageSearchAdvanced.class,
    EmployeeSearch.class,
    PayrollItemSearch.class,
    EmployeeSearchAdvanced.class,
    PayrollItemSearchAdvanced.class,
    SiteCategorySearch.class,
    SiteCategorySearchAdvanced.class,
    TimeSheetSearch.class,
    TimeEntrySearch.class,
    TimeBillSearch.class,
    TimeEntrySearchAdvanced.class,
    TimeBillSearchAdvanced.class,
    TimeSheetSearchAdvanced.class,
    CouponCodeSearch.class,
    CampaignSearch.class,
    PromotionCodeSearch.class,
    PromotionCodeSearchAdvanced.class,
    CouponCodeSearchAdvanced.class,
    CampaignSearchAdvanced.class,
    ItemDemandPlanSearch.class,
    ItemSupplyPlanSearch.class,
    ItemDemandPlanSearchAdvanced.class,
    ItemSupplyPlanSearchAdvanced.class,
    ManufacturingOperationTaskSearch.class,
    ManufacturingRoutingSearch.class,
    ManufacturingCostTemplateSearch.class,
    ManufacturingOperationTaskSearchAdvanced.class,
    ManufacturingRoutingSearchAdvanced.class,
    ManufacturingCostTemplateSearchAdvanced.class
})
public abstract class SearchRecord {


}
